<?php
/*------------------------------------------------
CLASSNAME:        campania
GENERATION DATE:	03.07.2020
CLASS FILE:       class.campania.php
FOR MYSQL TABLE: 	campanias
FOR MYSQL DB:     gp2020_dev
---------------------------------------------------
CODE GENERATED BY: dixernet
-------------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//==============================================================================================================
class campania
{ // class : begin

//ATTRIBUTE DECLARATION
//==============================================================================================================
var $idcampania;	// KEY ATTR. WITH AUTOINCREMENT
var $nombre;   		// (normal attribute)
var $database; 		// Instance of class database

//CONSTRUCTOR METHOD
//==============================================================================================================
function campania() {$this->database = new Database();}

//GETTER METHODS
//==============================================================================================================
function getIdcampania()	{return $this->idcampania;}
function getNombre() 			{return $this->nombre;}

// SETTER METHODS
//==============================================================================================================
function setIdcampania($val)	{$this->idcampania =  $val;}
function setNombre($val) 			{$this->nombre =  $val;}

//SELECT METHOD / LOAD
//==============================================================================================================
function select($id){
	$sql 		= "SELECT nombre FROM campanias WHERE idcampania = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idcampania	= $row->idcampania;
		$this->nombre 		= $row->nombre;
		return true;
	}
	else return false;
}

//DELETE
//==============================================================================================================
function delete($id){
	$sql = "SELECT * from premios where idcampania = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		return false;
	}	else {
		$sql = "DELETE FROM campanias WHERE idcampania = '$id'";
		$result = $this->database->query($sql);
		return true;
	}
}

// INSERT
//==============================================================================================================
function insert(){
	$this->idcampania = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO campanias (nombre) VALUES ($this->nombre)";
	$result = $this->database->query($sql);
	$this->idcampania = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==============================================================================================================
function update($id){
	$this->prepare();
	$sql = "UPDATE campanias SET nombre = $this->nombre WHERE idcampania = '$id'";
	$result = $this->database->query($sql);
	return true;
}

//==============================================================================================================
function prepare(){
	if($this->nombre != '') $this->nombre = '\''.$this->nombre.'\''; else $this->nombre = 'NULL';
}

// class : end
}
?>