<?php
/*------------------------------------------------------
CLASSNAME:        		canje
GENERATION DATE:	17.02.2017
CLASS FILE:       			canje.class.php
FOR MYSQL TABLE: 	canjes
FOR MYSQL DB:     		aper_quilmes
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/
if(!isset($_SESSION)) {session_start();}
include_once('class.database.php');

//CLASS DECLARATION
//==============================================================================================
class canje
{ // class : begin

//ATTRIBUTE DECLARATION
//==============================================================================================
var $idcanje;   		// KEY ATTR. WITH AUTOINCREMENT

var $idcliente;   	// (normal attribute)
var $idpremio;  		// (normal attribute)
var $estado;   			// (normal attribute)
var $fecha;   			// (normal attribute)
var $valor;   			// (normal attribute)
var $lugar_entrega;	// (normal attribute)
var $observaciones; // (normal attribute)

var $database;			// Instance of class database

//CONSTRUCTOR METHOD
//==============================================================================================
function canje()
{
	$this->database = new Database();
}

//GETTER METHODS
//==============================================================================================
function getIdcanje() 			{return $this->idcanje;}
function getIdcliente() 		{return $this->idcliente;}
function getIdpremio() 			{return $this->idpremio;}
function getEstado() 				{return $this->estado;}
function getFecha() 				{return $this->fecha;}
function getValor() 				{return $this->valor;}
function getLugar_entrega()	{return $this->lugar_entrega;}
function getObservaciones()	{return $this->observaciones;}

// SETTER METHODS
//==============================================================================================
function setIdcanje($val) 			{$this->idcanje = $val;}
function setIdcliente($val) 		{$this->idcliente = $val;}
function setIdpremio($val) 			{$this->idpremio = $val;}
function setEstado($val) 				{$this->estado = $val;}
function setFecha($val) 				{$this->fecha = $val;}
function setValor($val) 				{$this->valor = $val;}
function setLugar_entrega($val)	{$this->lugar_entrega = $val;}
function setObservaciones($val) {$this->observaciones = $val;}

//SELECT METHOD / LOAD
//==============================================================================================
function select($id){
	$sql 		= "SELECT * FROM canjes WHERE idcanje = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idcanje 				= $row->idcanje;
		$this->idcliente			= $row->idcliente;
		$this->idpremio 			= $row->idpremio;
		$this->estado 				= $row->estado;
		$this->fecha 					= $row->fecha;
		$this->valor 		  		= $row->valor;
		$this->lugar_entrega	= $row->lugar_entrega;
		$this->observaciones 	= $row->observaciones;
		return true;
	}
	else	return false;
}

//DELETE
//==============================================================================================
function delete($id){
	$sql = "DELETE FROM canjes WHERE idcanje = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function delete_todo($id){
	$sql = "DELETE FROM log_canjes WHERE idcanje = '$id'";
	$result = $this->database->query($sql);
	$sql1 = "DELETE FROM canjes WHERE idcanje = '$id'";
	$result1 = $this->database->query($sql1);
	return true;
}

// INSERT
//==============================================================================================
function insert(){
	$this->idcanje = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO canjes (idcliente,idpremio,estado,fecha,valor,lugar_entrega,observaciones) VALUES ($this->idcliente,$this->idpremio,$this->estado,'".date("Y-m-d h:i:s")."',$this->valor,$this->lugar_entrega,$this->observaciones)";
	$result = $this->database->query($sql);
	$this->idcanje = mysql_insert_id($this->database->link);
	$this->insertLog($this->idcanje, $this->estado);
	return true;
}

function insertLog($idcanje,$estado){
	if(isset($_SESSION['QLMS_idusuario']) && $_SESSION['QLMS_idusuario']!='')	
		$sql = "INSERT INTO log_canjes (idcanje,idusuario,estado,fecha) VALUES ($idcanje,".$_SESSION['QLMS_idusuario'].", $estado,'".date("Y-m-d h:i:s")."')";
	else
		$sql = "INSERT INTO log_canjes (idcanje,idusuario,estado,fecha) VALUES ($idcanje,".$_SESSION['QLMSF_idcliente'].",$estado,'".date("Y-m-d h:i:s")."')";
	$result = $this->database->query($sql);
	$this->idlog = mysql_insert_id($this->database->link);
}

// UPDATE
//==============================================================================================
function update($id){
	$this->prepare();
	$sql = "UPDATE canjes SET idcliente = $this->idcliente,idpremio = $this->idpremio,estado = $this->estado,fecha = ".date("Y-m-d h:i:s").",valor = $this->valor,lugar_entrega = $this->lugar_entrega,observaciones = $this->observaciones WHERE idcanje = '$id'";
	$result = $this->database->query($sql);
	$this->insertLog($id, $this->estado);
	return true;
}

function verifica(){
	$puntos = 0;
	$sql 		= "select sum(puntos) as puntos from puntos where idcliente = ".$this->idcliente;
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row3 = mysql_fetch_object($result)) {
		$puntos =	$row3->puntos;
	}

	$canjes = 0;
	$sql 		= "select sum(c.valor) as canjes from canjes c where c.idcliente = ".$this->idcliente." and c.estado not in ('anulado','devuelto')";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row2 = mysql_fetch_object($result)) {
		$canjes =	$row2->canjes;
	}

	$balance = $puntos-$canjes;
	if($balance>=$this->valor)
		return true;
	else
		return false;
}

function cambiaEstado($id,$estado){
	$sql = "UPDATE canjes SET estado = '$estado' WHERE idcanje = '$id'";
	$result = $this->database->query($sql);
	$estado = "'".$estado."'";
	$this->insertLog($id, $estado);
	return true;
}

function cambiaCodigo($id,$codigo){
	$sql = "UPDATE canjes SET seguimiento = '$codigo' WHERE idcanje = '$id'";
	$result = $this->database->query($sql);
	$estado = "'SE AGREGO CODIGO DE SEGUIMIENTO: ".$seguimiento."'";
	$this->insertLog($id, $estado);
	return true;
}

//========================================================================================
function prepare(){
	if($this->idcliente != '')			$this->idcliente			= '\''.$this->idcliente.'\'';			else $this->idcliente			= 'NULL';
	if($this->idpremio != '')				$this->idpremio				= '\''.$this->idpremio.'\'';			else $this->idpremio			= 'NULL';
	if($this->estado != '')					$this->estado					= '\''.$this->estado.'\'';				else $this->estado				= 'NULL';
	if($this->fecha	!= '')					$this->fecha					= '\''.$this->fecha.'\'';					else $this->fecha					= 'NULL';
	if($this->valor	!= '')					$this->valor					= '\''.$this->valor.'\'';					else $this->valor					= 'NULL';
	if($this->lugar_entrega != '')	$this->lugar_entrega	= '\''.$this->lugar_entrega.'\'';	else $this->lugar_entrega	= 'NULL';
	if($this->observaciones != '')	$this->observaciones	= '\''.$this->observaciones.'\'';	else $this->observaciones	= 'NULL';
}

function cleaner(){
	if($this->idcliente != '')			$this->idcliente			= '\''.$this->idcliente.'\'';			else $this->idcliente			= 'NULL';
	if($this->idpremio != '')				$this->idpremio				= '\''.$this->idpremio.'\'';			else $this->idpremio			= 'NULL';
	if($this->estado != '')					$this->estado					= '\''.$this->estado.'\'';				else $this->estado				= 'NULL';
	if($this->fecha	!= '')					$this->fecha					= '\''.$this->fecha.'\'';					else $this->fecha					= 'NULL';
	if($this->valor	!= '')					$this->valor					= '\''.$this->valor.'\'';					else $this->valor					= 'NULL';
	if($this->lugar_entrega != '')	$this->lugar_entrega	= '\''.$this->lugar_entrega.'\'';	else $this->lugar_entrega	= 'NULL';
	if($this->observaciones != '')	$this->observaciones	= '\''.$this->observaciones.'\'';	else $this->observaciones	= 'NULL';
}

//========================================================================================
function getHistorial(){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;

	$sql = "select * from log_canjes where idcanje = '$this->idcanje' order by fecha asc";

	$result = $this->database->query($sql);
	$result = $this->database->result;
	while ($row = mysql_fetch_object($result)){
		$arreglo[$i]['estado']	= $row->estado;
		$arreglo[$i]['fecha']		= $row->fecha;
		$i++;
	}
	//retornar el arreglo
	return $arreglo;
}

// class : end
}
?>