<?php
/*------------------------------------------------------
CLASSNAME:        		usuario
GENERATION DATE:	07.02.2017
CLASS FILE:       			class.usuario.php
FOR MYSQL TABLE:	usuarios
FOR MYSQL DB:     		aper_quilmes
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//==============================================================================================
class usuario
{ // class : begin

//ATTRIBUTE DECLARATION
//==============================================================================================
var $idusuario;  // KEY ATTR. WITH AUTOINCREMENT

var $tipo;   				// (normal attribute)
var $usuario;   	// (normal attribute)
var $clave;   			// (normal attribute)

var $database;	// Instance of class database

//CONSTRUCTOR METHOD
//==============================================================================================
function usuario()
{
	$this->database = new Database();
}

//GETTER METHODS
//==============================================================================================
function getIdusuario()	{return $this->idusuario;}
function getTipo() 					{return $this->tipo;}
function getUsuario() 		{return $this->usuario;}
function getClave() 				{return $this->clave;}

// SETTER METHODS
//==============================================================================================
function setIdusuario($val)	{$this->idusuario = $val;}
function setTipo($val) 					{$this->tipo = $val;}
function setUsuario($val) 		{$this->usuario = $val;}
function setClave($val) 				{$this->clave = $val;}

//SELECT METHOD / LOAD
//==============================================================================================
function select($id)
{
	$sql 		= "SELECT * FROM usuarios WHERE idusuario = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) 
	{
		$this->idusuario	= $row->idusuario;
		$this->tipo 					= $row->tipo;
		$this->usuario 		= $row->usuario;
		$this->clave 				= $row->clave;
		return true;
	} 
	else	return false;
}

//DELETE
//==============================================================================================
function delete($id)
{
	$sql = "DELETE FROM usuarios WHERE idusuario = '$id'";
	$result = $this->database->query($sql);
	return true;
}

// INSERT
//==============================================================================================
function validaInsert()
{
	$sql = "SELECT * FROM usuarios WHERE usuario = '$this->usuario' and clave = '$this->clave'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
		return false;
	else 
		return true;				
}

function insert()
{
	$this->idusuario = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO usuarios (tipo,usuario,clave) VALUES ($this->tipo,$this->usuario,$this->clave)";
	$result = $this->database->query($sql);
	$this->idusuario = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==============================================================================================
function validaUpdate()
{
	$sql = "SELECT * FROM usuarios WHERE usuario = '$this->usuario' and clave = '$this->clave' and idusuario <> '$this->idusuario'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
		return false;
	else 
		return true;				
}

function update($id)
{
	$this->prepare();
	$sql = "UPDATE usuarios SET usuario = $this->usuario,clave = $this->clave WHERE idusuario = '$id'";
	$result = $this->database->query($sql);
	return true;
}

//==============================================================================================
function prepare(){
	if($this->tipo != '')				$this->tipo				= '\''.$this->tipo.'\'';				else $this->tipo				= 'NULL';
	if($this->usuario != '')	$this->usuario	= '\''.$this->usuario.'\'';	else $this->usuario	= 'NULL';
	if($this->clave != '')			$this->clave			= '\''.$this->clave.'\'';			else $this->clave			= 'NULL';
}

// class : end
}
?>