<?php
/*--------------------------------------
CLASSNAME:    login
CLASS FILE:   class.login.php
FOR MYSQL DB:	gp2020_dev
-----------------------------------------
CODE GENERATED BY: dixer
--------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//====================================================================================================
class login
{ // class : begin

//ATTRIBUTE DECLARATION
//====================================================================================================
var $database; // Instance of class database

//CONSTRUCTOR METHOD
//====================================================================================================
function login()
{
	$this->database = new Database();
}

//SELECT METHOD / LOAD
//======================================================================================================
function logger($usuario, $clave){
	if(!isset($_SESSION)) {session_start();}
	$sql 		= "select * from usuarios where usuario = '$usuario' and clave = '$clave'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row = mysql_fetch_object($result)){
		$_SESSION['QLMS_logged'] 		= 1;
		$_SESSION['QLMS_usuario']		= $row->usuario;
		$_SESSION['QLMS_idusuario']	= $row->idusuario;
		$_SESSION['QLMS_tipo']			= $row->tipo;
		return true;
	}	else {
	 	$_SESSION['QLMS_logged'] = 0;
	 	return false;
	}	
}	

//====================================================================================================
function loggerFront($codigo, $clave){
	if(!isset($_SESSION)) {session_start();}
	$sql = "select * from socios where codigo = '$codigo' and clave = '$clave'";

	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row = mysql_fetch_object($result)){
		$_SESSION['QLMSF_admin']				= 0;
		$_SESSION['QLMSF_logged'] 			= 1;
		$_SESSION['QLMSF_idcliente']		= $row->idsocio;
		$_SESSION['QLMSF_idgrupo']			= $row->idtipo;
		$_SESSION['QLMSF_codigo_unico']	= $row->codigo;
		$vars = preg_split('/,/',$row->region);
		$region = $vars[0];
		$_SESSION['QLMSF_region']				= $region;
		$_SESSION['QLMSF_rango']				= $row->rango;
		$_SESSION['QLMSF_ejecutivo']		= $row->ejecutivo;
		$_SESSION['QLMSF_jefe']					= $row->jefe;
		$_SESSION['QLMSF_gerente']			= $row->gerente;
		$_SESSION['QLMSF_nombre']				= $row->nombre;
		$_SESSION['QLMSF_apellido']			= $row->apellido;
		$_SESSION['QLMSF_email']				=	$row->email;
		$_SESSION['QLMSF_domicilio']		= $row->direccion;
		$_SESSION['QLMSF_localidad']		= $row->localidad;
		$_SESSION['QLMSF_provincia']		= $row->provincia;
		$_SESSION['QLMSF_telefono']			= $row->telefono;

		//update de lastlog
		$sql = 'update socios set lastlog = NOW() where idsocio = '.$row->idsocio;
		$result = $this->database->query($sql);

		$puntos = 0;
		$sql 		= "select sum(puntos) as puntos from puntos where idcliente = ".$row->idsocio;
		$result = $this->database->query($sql);
		$result = $this->database->result;
		if ($row3 = mysql_fetch_object($result)) {
			$puntos =	$row3->puntos;
		}

		$canjes = 0;
		$sql 		= "select sum(valor) as canjes from canjes where idcliente = ".$row->idsocio." and estado not in ('anulado','devuelto')";
		$result = $this->database->query($sql);
		$result = $this->database->result;
		if ($row2 = mysql_fetch_object($result)) {
			$canjes =	$row2->canjes;
		}
		$_SESSION['QLMSF_puntos'] = ($puntos - $canjes);

		/*
		$sql 		= "SELECT idcliente, puntos, canjes, balance FROM ranking order by balance desc";
		$result = $this->database->query($sql);
		$result = $this->database->result;
		$puesto = 0;
		while ($row2 = mysql_fetch_object($result)) {
			$puesto++;
			if($row2->idcliente == $row->idsocio) {
				$_SESSION['QLMSF_ranking'] = $puesto;
				break;
			}	
		}


		$sql = "select sum(puntos) as suma, idcliente from puntos group by idcliente order by suma desc";
		$result = $this->database->query($sql);
		$result = $this->database->result;
		$puesto = 0;
		$_SESSION['QLMSF_ranking'] = $puesto;
		while ($row2 = mysql_fetch_object($result)) {
			$puesto++;
			if($row2->idcliente == $row->idsocio) {
				$_SESSION['QLMSF_ranking'] = $puesto;
				break;
			}	
		}*/
		$mes_actual = date('m');
		$anio_actual = date('Y');
		$sql = "SELECT ranking_total as ranking FROM puntos WHERE idcliente = '$row->idsocio' order by fecha desc limit 1";

		$result = $this->database->query($sql);
		$result = $this->database->result;
		$puesto = 0;
		$_SESSION['QLMSF_ranking'] = $puesto;
		if ($row2 = mysql_fetch_object($result)) {
			$puesto = $row2->ranking;
		}
		if($puesto=='NULL' || $puesto=='') $puesto = 0;
		$_SESSION['QLMSF_ranking'] = $puesto;

		return true;
	}	else {
	 	$_SESSION['QLMSF_logged'] = 0;
	 	return false;
	}
}

//====================================================================================================
function loggerFrontAdmin($clave){
	if(!isset($_SESSION)) {session_start();}

	$sql 		= "select * from socios where clave = '$clave'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row = mysql_fetch_object($result))	{
		$_SESSION['QLMSF_admin'] 			= 1;
		$_SESSION['QLMSF_logged'] 		= 1;
		$_SESSION['QLMSF_idcliente']	= $row->idsocio;
		$_SESSION['QLMSF_nombre']			= 'OPERADOR COMO: ';

		$puntos = 0;
		$sql 		= "select sum(puntos) as puntos from puntos where idcliente = ".$row->idsocio;
		$result = $this->database->query($sql);
		$result = $this->database->result;
		if ($row3 = mysql_fetch_object($result)) {
			$puntos =	$row3->puntos;
		}

		$canjes = 0;
		$sql 		= "select sum(valor) as canjes from canjes where idcliente = ".$row->idsocio." and estado <> 'anulado'";
		$result = $this->database->query($sql);
		$result = $this->database->result;
		if ($row2 = mysql_fetch_object($result)) {
			$canjes =	$row2->canjes;
		}
		$_SESSION['QLMSF_puntos'] = $puntos - $canjes;
		return true;
	}
	else
	{
	 	$_SESSION['QLMSF_logged'] = 0;
	 	return false;
	}	
}

// class : end
}
?>