<?php
/*------------------------------------------------------
CLASSNAME:       	socio
GENERATION DATE: 	07.07.2020
CLASS FILE:      	class.socio.php
FOR MYSQL TABLE:	socios
FOR MYSQL DB:     gp2020_dev
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//========================================================================================================================
class socio
{ // class : begin

//ATTRIBUTE DECLARATION
//========================================================================================================================
var $idsocio;   // KEY ATTR. WITH AUTOINCREMENT

var $idtipo;   	// (normal attribute)
var $codigo;   	// (normal attribute)
var $region;   	// (normal attribute)
var $rango;   	// (normal attribute)
var $ejecutivo;	// (normal attribute)
var $jefe;			// (normal attribute)
var $gerente;		// (normal attribute)
var $nombre;   	// (normal attribute)
var $apellido;  // (normal attribute)
var $email;   	// (normal attribute)
var $clave;   	// (normal attribute)
var $direccion; // (normal attribute)
var $localidad; // (normal attribute)
var $provincia; // (normal attribute)
var $telefono;  // (normal attribute)
var $fechaalta; // (normal attribute)

var $database; 	// Instance of class database

//CONSTRUCTOR METHOD
//========================================================================================================================
function socio(){$this->database = new Database();}

//GETTER METHODS
//========================================================================================================================
function getIdsocio() 	{return $this->idsocio;}
function getIdtipo() 		{return $this->idtipo;}
function getCodigo() 		{return $this->codigo;}
function getRegion() 		{return $this->region;}
function getRango() 		{return $this->rango;}
function getEjecutivo() {return $this->ejecutivo;}
function getJefe() 			{return $this->jefe;}
function getGerente() 	{return $this->gerente;}
function getNombre() 		{return $this->nombre;}
function getApellido() 	{return $this->apellido;}
function getEmail() 		{return $this->email;}
function getClave() 		{return $this->clave;}
function getDireccion()	{return $this->direccion;}
function getLocalidad()	{return $this->localidad;}
function getProvincia()	{return $this->provincia;}
function getTelefono() 	{return $this->telefono;}
function getFechaalta()	{return $this->fechaalta;}

// SETTER METHODS
//========================================================================================================================
function setIdsocio($val) 	{$this->idsocio = $val;}
function setIdtipo($val) 		{$this->idtipo = $val;}
function setCodigo($val) 		{$this->codigo = $val;}
function setRegion($val) 		{$this->region = $val;}
function setRango($val) 		{$this->rango = $val;}
function setEjecutivo($val) {$this->ejecutivo = $val;}
function setJefe($val) 			{$this->jefe = $val;}
function setGerente($val) 	{$this->gerente = $val;}
function setNombre($val) 		{$this->nombre = $val;}
function setApellido($val) 	{$this->apellido = $val;}
function setEmail($val) 		{$this->email = $val;}
function setClave($val) 		{$this->clave = $val;}
function setDireccion($val) {$this->direccion = $val;}
function setLocalidad($val) {$this->localidad = $val;}
function setProvincia($val) {$this->provincia = $val;}
function setTelefono($val) 	{$this->telefono = $val;}
function setFechaalta($val)	{$this->fechaalta = $val;}

//SELECT METHOD / LOAD
//========================================================================================================================
function select($id){
	$sql 		= "SELECT * FROM socios WHERE idsocio = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_codigo($cd){
	$sql 		= "SELECT * FROM socios WHERE codigo = '$cd'";

	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_email($email){
	$sql 		= "SELECT * FROM socios WHERE email = '$email'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_region($rg){
	$sql 		= "SELECT * FROM socios WHERE region = '$rg'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_rango($rng){
	$sql 		= "SELECT * FROM socios WHERE rango = '$rng'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_ejecutivo($ej){
	$sql 		= "SELECT * FROM socios WHERE ejecutivo = '$ej'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_jefe($jf){
	$sql 		= "SELECT * FROM socios WHERE jefe = '$jf'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_gerente($gr){
	$sql 		= "SELECT * FROM socios WHERE gerente = '$gr'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idsocio = $row->idsocio;
		$this->idtipo = $row->idtipo;
		$this->codigo = $row->codigo;
		$this->region = $row->region;
		$this->rango = $row->rango;
		$this->ejecutivo = $row->ejecutivo;
		$this->jefe = $row->jefe;
		$this->gerente = $row->gerente;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->email = $row->email;
		$this->clave = $row->clave;
		$this->direccion = $row->direccion;
		$this->localidad = $row->localidad;
		$this->provincia = $row->provincia;
		$this->telefono = $row->telefono;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

//DELETE
//========================================================================================================================
function delete($id){
	$sql = "DELETE FROM socios WHERE idsocio = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function delete_todo($id){
	$sql = "DELETE FROM concursos_clientes WHERE idcliente = '$id'";
	$result = $this->database->query($sql);
	$sql0 = "DELETE FROM puntos WHERE idcliente = '$id'";
	$result0 = $this->database->query($sql0);
	$sql1 = "DELETE FROM socios WHERE idsocio = '$id'";
	$result1 = $this->database->query($sql1);
	return true;
}

//INSERT
//========================================================================================================================
function insert(){
	$this->idsocio = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO socios (idtipo,codigo,region,rango,ejecutivo,jefe,gerente,nombre,apellido,email,clave,direccion,localidad,provincia,telefono,fechaalta) VALUES ($this->idtipo,$this->codigo,$this->region,$this->rango,$this->ejecutivo,$this->jefe,$this->gerente,$this->nombre,$this->apellido,$this->email,$this->clave,$this->direccion,$this->localidad,$this->provincia,$this->telefono,'".date("Y-m-d")."')";
	$result = $this->database->query($sql);
	$this->idsocio = mysql_insert_id($this->database->link);
	return true;
}

//UPDATE
//========================================================================================================================
function update($id){
	$this->prepare();
	$sql = "UPDATE socios SET idtipo = $this->idtipo,codigo = $this->codigo,region = $this->region,rango = $this->rango,ejecutivo = $this->ejecutivo,jefe = $this->jefe,gerente = $this->gerente,nombre = $this->nombre,apellido = $this->apellido,email = $this->email,clave = $this->clave,direccion = $this->direccion,localidad = $this->localidad,provincia = $this->provincia,telefono = $this->telefono WHERE idsocio = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function actualizaSaldo($id){
	$puntos = 0;
	$sql 		= "select sum(puntos) as puntos from puntos where idcliente = ".$id;
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row3 = mysql_fetch_object($result)) {
		$puntos =	$row3->puntos;
	}

	$canjes = 0;
	$sql 		= "select sum(valor) as canjes from canjes where idcliente = ".$id." and estado <> 'anulado' and estado <> 'devuelto'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row2 = mysql_fetch_object($result)) {
		$canjes =	$row2->canjes;
	}
	$saldo = $puntos - $canjes;
	$_SESSION['QLMSF_puntos'] = $saldo;
	return $saldo;
}

//========================================================================================================================
function prepare(){
	$this->idtipo = str_replace("'", "", $this->idtipo);
	$this->codigo = str_replace("'", "", $this->codigo);
	$this->region = str_replace("'", "", $this->region);
	$this->rango = str_replace("'", "", $this->rango);
	$this->ejecutivo = str_replace("'", "", $this->ejecutivo);
	$this->jefe = str_replace("'", "", $this->jefe);
	$this->gerente = str_replace("'", "", $this->gerente);
	$this->nombre = str_replace("'", "", $this->nombre);
	$this->apellido = str_replace("'", "", $this->apellido);
	$this->email = str_replace("'", "", $this->email);
	$this->clave = str_replace("'", "", $this->clave);
	$this->direccion = str_replace("'", "", $this->direccion);
	$this->localidad = str_replace("'", "", $this->localidad);
	$this->provincia = str_replace("'", "", $this->provincia);
	$this->telefono = str_replace("'", "", $this->telefono);
	
	if($this->idtipo != '')			$this->idtipo			= '\''.$this->idtipo.'\'';								else $this->idtipo		= 'NULL';
	if($this->codigo != '')			$this->codigo			= '\''.$this->codigo.'\'';								else $this->codigo		= 'NULL';
	if($this->region != '')			$this->region			= '\''.$this->region.'\'';								else $this->region		= 'NULL';
	if($this->rango != '')			$this->rango			= '\''.addslashes($this->rango).'\'';			else $this->rango			= 'NULL';
	if($this->ejecutivo != '')	$this->ejecutivo	= '\''.$this->ejecutivo.'\'';							else $this->ejecutivo	= 'NULL';
	if($this->jefe != '')				$this->jefe				= '\''.$this->jefe.'\'';									else $this->jefe			= 'NULL';
	if($this->gerente != '')		$this->gerente		= '\''.$this->gerente.'\'';								else $this->gerente		= 'NULL';
	if($this->nombre != '')			$this->nombre			= '\''.addslashes($this->nombre).'\'';		else $this->nombre		= 'NULL';
	if($this->apellido != '')		$this->apellido		= '\''.addslashes($this->apellido).'\'';	else $this->apellido	= 'NULL';
	if($this->email	!= '')			$this->email			= '\''.$this->email.'\'';									else $this->email			= 'NULL';
	if($this->clave != '')			$this->clave			= '\''.$this->clave.'\'';									else $this->clave			= 'NULL';
	if($this->direccion != '')	$this->direccion	= '\''.addslashes($this->direccion).'\''; else $this->direccion	= 'NULL';
	if($this->localidad != '')	$this->localidad	= '\''.addslashes($this->localidad).'\''; else $this->localidad	= 'NULL';
	if($this->provincia != '')	$this->provincia	= '\''.addslashes($this->provincia).'\''; else $this->provincia	= 'NULL';
	if($this->telefono != '')		$this->telefono		= '\''.$this->telefono.'\'';							else $this->telefono	= 'NULL';
}

function resetea(){
	$this->codigo = '';
	$this->region = '';
	$this->rango = '';
	$this->ejecutivo = '';
	$this->jefe = '';
	$this->gerente = '';
	$this->nombre = '';
	$this->apellido = '';
	$this->email	= '';
	$this->clave = '';
	$this->direccion = '';
	$this->localidad = '';
	$this->provincia = '';
	$this->telefono = '';
}

//========================================================================================================================
function getCanjes(){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;

	$sql = "select c.*, pr.nombre as premio, pr.tipo as tipo, pr.imagen as fotopremio from canjes c, premios pr where c.idcliente = '$this->idsocio' and c.idpremio = pr.idpremio order by c.fecha desc";

	$result = $this->database->query($sql);
	$result = $this->database->result;
	while ($row = mysql_fetch_object($result)){
		$arreglo[$i]['idcanje']				= $row->idcanje;
		$arreglo[$i]['idcliente']			= $row->idcliente;
		$arreglo[$i]['idpremio']			= $row->idpremio;
		$arreglo[$i]['tipo']					= $row->tipo;
		$arreglo[$i]['premio']				= $row->premio;
		$arreglo[$i]['fotopremio']		= $row->fotopremio;
		$arreglo[$i]['estado']				= $row->estado;
		$arreglo[$i]['fecha']					= $row->fecha;
		$arreglo[$i]['email']					= $row->email;
		$arreglo[$i]['seguimiento']		= $row->seguimiento;
		$arreglo[$i]['valor']					= $row->valor;
		$arreglo[$i]['lugar_entrega']	= $row->lugar_entrega;
		$arreglo[$i]['observaciones']	= $row->observaciones;
		$i++;
	}
	//retornar el arreglo
	return $arreglo;
}

//========================================================================================================================
function getMovimientos($orden,$limit=''){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;

	$sql.= "(select '' as idpremio, 'ingreso de millas' as tipo, observaciones, puntos as numero, fecha as fecha, '' as estado from puntos where idcliente = '$this->idsocio') ";
	$sql.= ' union all ';
	$sql.= "(select pr.idpremio, 'canje' as tipo, '' as observaciones, c.valor as numero, c.fecha as fecha, c.estado from canjes c, premios pr where c.idcliente = '$this->idsocio' and c.estado <> 'anulado' and c.estado <> 'devuelto' and c.idpremio = pr.idpremio)  ";
	$sql.= ' union all ';
	$sql.= "(select pr.idpremio, 'canje' as tipo, '' as observaciones, '0' as numero, c.fecha as fecha, c.estado from canjes c, premios pr where c.idcliente = '$this->idsocio' and (c.estado = 'anulado' or c.estado = 'devuelto') and c.idpremio = pr.idpremio)  ";
	$sql.= 'order by fecha '.$orden;
	if($limit != '') $sql .= ' limit 0,'.$limit;
	
	$result = $this->database->query($sql);
	$result = $this->database->result;
	while ($row = mysql_fetch_object($result)){
		$arreglo[$i]['tipo']					= $row->tipo;
		$arreglo[$i]['observaciones']	= $row->observaciones;
		$arreglo[$i]['idpremio']			= $row->idpremio;
		$arreglo[$i]['estado']				= $row->estado;
		$arreglo[$i]['numero']				= $row->numero;
		$arreglo[$i]['fecha']					= $row->fecha;
		$i++;
	}
	//retornar el arreglo
	return $arreglo;
}

//========================================================================================================================
function dameSumaXConcepto($tabla,$campo,$concepto='',$estado1='',$estado2='') {
	$sql = "SELECT SUM(".$campo.") as sumatoria FROM ".$tabla." WHERE idcliente = '$this->idsocio'";
	if($estado1 != '') $sql .= " and estado <> '".$estado1."'";
	if($estado2 != '') $sql .= " and estado <> '".$estado2."'";
	if($concepto != '') $sql .= " and linea like '%".$concepto."%'";
	
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row	= mysql_fetch_object($result)){
		if($row->sumatoria>0)
			return $row->sumatoria;
		else
			return 0;
	}
	else
		return 0;
}

//========================================================================================================================
function dameChancesTotalesId($idp) {
	$sql = "SELECT SUM(puntos) as puntos FROM puntos WHERE idcliente = '$idp'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row	= mysql_fetch_object($result)){
		if($row->puntos>0)
			return $row->puntos;
		else
			return 0;
	}
	else
		return 0;
}

//========================================================================================================================
function dameBalanceId($idp) {
	$sql2 = "select SUM(puntos) as ingresos from puntos where idcliente = '$idp'";
	$result2 = $this->database->query($sql2);
	$result2 = $this->database->result;
	if($row2 = mysql_fetch_object($result2)){
		if(intval($row2->ingresos) >= 0)
			$suma = intval($row2->ingresos);
		else
			$suma = 0;
	}
	else $suma = 0;

	$sql3 = "select SUM(valor) as egresos from canjes where idcliente = '$idp' and estado <> 'anulado' and estado <> 'devuelto'";
	$result3 = $this->database->query($sql3);
	$result3 = $this->database->result;
	if($row3 = mysql_fetch_object($result3)){
		if(intval($row3->egresos) >= 0)
			$resta = intval($row3->egresos);
		else
			$resta = 0;
	}
	else $resta = 0;

	$resultado_final = intval($suma - $resta);
	return $resultado_final;
}

// class : end
}
?>