<?php
/*------------------------------------------------------
CLASSNAME:        grupo
GENERATION DATE:	03.07.2020
CLASS FILE:       class.grupo.php
FOR MYSQL TABLE:	grupos
FOR MYSQL DB:     gp2020_dev
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/
include_once('class.database.php');

//CLASS DECLARATION
//==================================================================================================
class grupo
{ // class : begin

//ATTRIBUTE DECLARATION
//==================================================================================================
var $idgrupo;   	// KEY ATTR. WITH AUTOINCREMENT
var $nombre;   		// (normal attribute)
var $descripcion;	// (normal attribute)
var $database; 		// Instance of class database

//CONSTRUCTOR METHOD
//==================================================================================================
function grupo() {$this->database = new Database();}

//GETTER METHODS
//==================================================================================================
function getIdgrupo() 		{return $this->idgrupo;}
function getNombre() 			{return $this->nombre;}
function getDescripcion()	{return $this->descripcion;}

// SETTER METHODS
//==================================================================================================
function setIdgrupo($val) 		{$this->idgrupo =  $val;}
function setNombre($val) 			{$this->nombre =  $val;}
function setDescripcion($val)	{$this->descripcion =  $val;}

//SELECT METHOD / LOAD
//==================================================================================================
function select($id){
	$sql 		= "SELECT * FROM grupos WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)){
		$this->idgrupo 			= $row->idgrupo;
		$this->nombre 			= $row->nombre;
		$this->descripcion	= $row->descripcion;
		return true;
	} 
	else	return false;
}

//DELETE
//==================================================================================================
function delete($id){
	$sql = "DELETE FROM grupos WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function delete_todo($id){
	$sql = "DELETE FROM premios_grupos WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	$sql1 = "DELETE FROM grupos WHERE idgrupo = '$id'";
	$result1 = $this->database->query($sql1);
	return true;
}

// INSERT
//==================================================================================================
function insert(){
	$this->idgrupo = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO grupos (nombre,descripcion) VALUES ($this->nombre,$this->descripcion)";
	$result = $this->database->query($sql);
	$this->idgrupo = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==================================================================================================
function update($id){
	$this->prepare();
	$sql = "UPDATE grupos SET nombre = $this->nombre, descripcion = $this->descripcion WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	return true;
}

//==================================================================================================
function prepare(){
	if($this->nombre != '')			 $this->nombre			= '\''.$this->nombre.'\''; 			else $this->nombre			= 'NULL';
	if($this->descripcion != '') $this->descripcion	= '\''.$this->descripcion.'\''; else $this->descripcion	= 'NULL';
}

// class : end
}
?>