<?php
/*---------------------------------------------------------
CLASSNAME:        		grupos_premio
GENERATION DATE:  28.05.2018
CLASS FILE:       			grupos_premio.class.php
FOR MYSQL TABLE:	grupos_premio
FOR MYSQL DB:     		aper_quilmes
-----------------------------------------------------------
CODE GENERATED BY: dixernet
--------------------------------=-----------------------*/
include_once('class.database.php');

//CLASS DECLARATION
//==================================================================================================================================
class grupos_premio
{ // class : begin

//ATTRIBUTE DECLARATION
//==================================================================================================================================
var $idpremio_grupo;	// KEY ATTR. WITH AUTOINCREMENT
var $idpremio;   					// (normal attribute)
var $idgrupo;   						// (normal attribute)
var $database; 						// Instance of class database

//CONSTRUCTOR METHOD
//==================================================================================================================================
function grupos_premio(){
	$this->database = new Database();
}

//GETTER METHODS
//==================================================================================================================================
function getIdpremiogrupo()	{return $this->idpremio_grupo;}
function getIdpremio() 					{return $this->idpremio;}
function getIdgrupo() 						{return $this->idgrupo;}

// SETTER METHODS
//==================================================================================================================================
function setIdpremiogrupo($val)	{$this->idpremio_grupo =  $val;}
function setIdpremio($val) 					{$this->idpremio =  $val;}
function setIdgrupo($val) 						{$this->idgrupo =  $val;}

//SELECT METHOD / LOAD
//==================================================================================================================================
function select($id){
	$sql 		= "SELECT * FROM premios_grupos WHERE idpremio_grupo = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row	= mysql_fetch_object($result)){
		$this->idpremio_grupo	= $row->idpremio_grupo;
		$this->idpremio 						= $row->idpremio;
		$this->idgrupo 							= $row->idgrupo;
		return true;
	}
	else	return false;
}

function selectXpremio($idpremio){
	$sql 		= "SELECT idgrupo FROM premios_grupos WHERE idpremio = '$idpremio'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row	= mysql_fetch_object($result)){
		$this->idgrupo = $row->idgrupo;
		return true;
	}
	else	return false;
}

//DELETE
//==================================================================================================================================
function delete($id){
	$sql = "DELETE FROM premios_grupos WHERE idpremio_grupo = '$id'";
	$result = $this->database->query($sql);
}

function deleteXpremio($idpremio){
	$sql = "DELETE FROM premios_grupos WHERE idpremio = '$idpremio'";
	$result = $this->database->query($sql);
}

// INSERT
//==================================================================================================================================
function insert(){
	$this->idpremio_grupo = ''; // clear key for autoincrement	
	$sql = "INSERT INTO premios_grupos (idpremio,idgrupo) VALUES ($this->idpremio,$this->idgrupo)";
	$result = $this->database->query($sql);
	$this->idpremio_grupo = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==================================================================================================================================
function update($id){
	if($this->idpremio	!= '')	$this->idpremio	= '\''.$this->idpremio.'\'';	else $this->idpremio	= 'NULL';
	if($this->idgrupo	!= '')		$this->idgrupo		= '\''.$this->idgrupo.'\'';	else $this->idgrupo	= 'NULL';
	$sql = "UPDATE premios_grupos SET idpremio = $this->idpremio,idgrupo = $this->idgrupo WHERE idpremio_grupo = '$id'";
	$result = $this->database->query($sql);
	return true;
}

// class : end
}
?>