<?php
/*--------------------------------------
CLASSNAME:     	login
CLASS FILE:     	class.login.php
FOR MYSQL DB:	aper_quilmes
-----------------------------------------
CODE GENERATED BY: dixer
--------------------------------------*/

include_once("class.database.php");

//CLASS DECLARATION
//====================================================================================================
class login
{ // class : begin

//ATTRIBUTE DECLARATION
//====================================================================================================
var $database; // Instance of class database

//CONSTRUCTOR METHOD
//====================================================================================================
function login()
{
	$this->database = new Database();
}

//SELECT METHOD / LOAD
//======================================================================================================
function logger($usuario, $clave)
{
	if(!isset($_SESSION)) {session_start();}
	$sql 		= "select * from usuarios where usuario = '$usuario' and clave = '$clave'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row = mysql_fetch_object($result))
	{
		$_SESSION['QLMS_logged'] 		= 1;					
		$_SESSION['QLMS_usuario']		= $row->usuario;		
		$_SESSION['QLMS_idusuario']	= $row->idusuario;					
		$_SESSION['QLMS_tipo']					= $row->tipo;
		return true;	
	}
	else
	{
	 	$_SESSION['QLMS_logged'] = 0;
	 	return false;
	}	
}	

//====================================================================================================
function loggerFront($email, $clave)
{
	if(!isset($_SESSION)) {session_start();}
	$sql 		= "select * from clientes where estado in ('A','C','S') and email = '$email' and clave = '$clave'";
	
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row = mysql_fetch_object($result))
	{
		$_SESSION['QLMSF_admin']		= 0;		
		$_SESSION['QLMSF_logged'] 		= 1;		
		$_SESSION['QLMSF_idcliente']	= $row->idcliente;
		
		if($row->idgrupo != '')	
			$_SESSION['QLMSF_idgrupo']	= $row->idgrupo;		
		else
			$_SESSION['QLMSF_idgrupo']	= 0;		
		
		$_SESSION['QLMSF_email']		= $row->email;		
		$_SESSION['QLMSF_domicilio']	= $row->domicilio;		
		$_SESSION['QLMSF_provincia']	= $row->domicilio_provincia;		
		$_SESSION['QLMSF_localidad']	= $row->domicilio_localidad;		
		$_SESSION['QLMSF_codigo_unico']	= $row->codigo_unico;		
		$_SESSION['QLMSF_cp']			= $row->domicilio_cp;		
		$_SESSION['QLMSF_nombre']		= $row->nombre;
		$_SESSION['QLMSF_apellido']		= $row->apellido;
		$_SESSION['QLMSF_estado']		= $row->estado;
		$_SESSION['QLMSF_razon_social']	= $row->razon_social;		
		$_SESSION['QLMSF_foto']			= '';		
		$_SESSION['QLMSF_dni']			= $row->dni;
		$_SESSION['QLMSF_estado']		= $row->estado;		
		
		//update de lastlog
		$sql 	= "update clientes set lastlog = NOW() where idcliente = ".$row->idcliente;
		$result = $this->database->query($sql);
				
		$puntos = 0;
		$sql 		= "select sum(puntos) as puntos from puntos where idcliente = ".$row->idcliente;
		$result = $this->database->query($sql);
		$result = $this->database->result;
		if ($row3 = mysql_fetch_object($result)) {
			$puntos =	$row3->puntos;
		}
			
		$canjes = 0;
		$sql 		= "select sum(valor) as canjes from canjes where idcliente = ".$row->idcliente." and estado not in ('anulado','devuelto')";
		$result = $this->database->query($sql);
		$result = $this->database->result;
		if ($row2 = mysql_fetch_object($result)) {
			$canjes =	$row2->canjes;
		}
		$_SESSION['QLMSF_puntos'] = ($puntos - $canjes);
		
		/*
		$sql 		= "SELECT idcliente, puntos, canjes, balance FROM ranking order by balance desc";		
		$result = $this->database->query($sql);
		$result = $this->database->result;
		$puesto = 0;
		while ($row2 = mysql_fetch_object($result)) {
			$puesto++;
			if($row2->idcliente == $row->idcliente) {
				$_SESSION['QLMSF_ranking'] = $puesto;
				break;
			}	
		}
		*/
		
		$sql 	= "select sum(puntos) as suma, idcliente from puntos group by idcliente order by suma desc";		
		$result = $this->database->query($sql);
		$result = $this->database->result;
		$puesto = 0;
		while ($row2 = mysql_fetch_object($result)) {
			$puesto++;
			if($row2->idcliente == $row->idcliente) {
				$_SESSION['QLMSF_ranking'] = $puesto;
				break;
			}	
		}
		return true;
	}
	else
	{
	 	$_SESSION['QLMSF_logged'] = 0;
	 	return false;
	}	
}

//====================================================================================================
function loggerFrontAdmin($clave)
{
	if(!isset($_SESSION)) {session_start();}
		
	$sql 		= "select * from clientes where clave = '$clave' and estado in ('A','C','S')"; 
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row = mysql_fetch_object($result))
	{
		if ($row->estado == 'A' || $row->estado == 'C')
		{
			$_SESSION['QLMSF_admin'] 			= 1;		
			$_SESSION['QLMSF_logged'] 		= 1;		
			$_SESSION['QLMSF_idcliente']	= $row->idcliente;		
			$_SESSION['QLMSF_nombre']		= 'OPERADOR COMO: ';
			$_SESSION['QLMSF_foto']					= $row->foto;		
			
			$puntos = 0;
			$sql 		= "select sum(puntos) as puntos from puntos where idcliente = ".$row->idcliente;
			$result = $this->database->query($sql);
			$result = $this->database->result;
			if ($row3 = mysql_fetch_object($result)) {
				$puntos =	$row3->puntos;
			}
			
			$canjes = 0;
			$sql 		= "select sum(valor) as canjes from canjes where idcliente = ".$row->idcliente." and estado <> 'anulado'";
			$result = $this->database->query($sql);
			$result = $this->database->result;
			if ($row2 = mysql_fetch_object($result)) {
				$canjes =	$row2->canjes;
			}
			$_SESSION['QLMSF_puntos'] = $puntos - $canjes;
			return true;
		}
		else
		{
			$_SESSION['QLMSF_logged'] = 0;
			return $row->estado;
		}
	}
	else
	{
	 	$_SESSION['QLMSF_logged'] = 0;
	 	return false;
	}	
}

// class : end
}
?>