<?php
/*------------------------------------------------------
CLASSNAME:        		cliente
GENERATION DATE: 10.02.2017
CLASS FILE:       			class.cliente.php
FOR MYSQL TABLE:	clientes
FOR MYSQL DB:     		aper_quilmes
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//==================================================================================================================================
class cliente
{ // class : begin


//ATTRIBUTE DECLARATION
//==================================================================================================================================
var $idcliente;   									// KEY ATTR. WITH AUTOINCREMENT
var $idgrupo;   									// (normal attribute)
var $codigo_cliente;   				// (normal attribute)
var $codigo_unico;   					// (normal attribute)
var $razon_social;   					// (normal attribute)
var $nombre;   									// (normal attribute)
var $apellido;   									// (normal attribute)
var $clave;   											// (normal attribute)
var $email;   											// (normal attribute)
var $cuit;   												// (normal attribute)
var $domicilio;   								// (normal attribute)
var $domicilio_localidad;		// (normal attribute)
var $domicilio_provincia;		// (normal attribute)
var $domicilio_cp;   						// (normal attribute)
var $tel_movil;   								// (normal attribute)
var $tel_otro;   									// (normal attribute)
var $acepta_basesycond;	// (normal attribute)
var $estado;   										// (normal attribute)
var $fechaalta;   								// (normal attribute)
var $database; 									// Instance of class database


//CONSTRUCTOR METHOD
//==================================================================================================================================
function cliente()
{
	$this->database = new Database();
}

//GETTER METHODS
//==================================================================================================================================
function getIdcliente() {return $this->idcliente;}
function getIdgrupo() {return $this->idgrupo;}
function getCodigo_cliente() {return $this->codigo_cliente;}
function getCodigo_unico() {return $this->codigo_unico;}
function getRazon_social() {return $this->razon_social;}
function getNombre() {return $this->nombre;}
function getApellido() {return $this->apellido;}
function getClave() {return $this->clave;}
function getEmail() {return $this->email;}
function getCuit() {return $this->cuit;}
function getDomicilio() {return $this->domicilio;}
function getDomicilio_localidad() {return $this->domicilio_localidad;}
function getDomicilio_provincia() {return $this->domicilio_provincia;}
function getDomicilio_cp() {return $this->domicilio_cp;}
function getTel_movil() {return $this->tel_movil;}
function getTel_otro() {return $this->tel_otro;}
function getAcepta_basesycond() {return $this->acepta_basesycond;}
function getDni() {return $this->dni;}
function getEstado() {return $this->estado;}
function getFechaalta() {return $this->fechaalta;}

// SETTER METHODS
//==================================================================================================================================
function setIdcliente($val) {$this->idcliente = $val;}
function setIdgrupo($val) {$this->idgrupo = $val;}
function setDni($val) {$this->dni = $val;}
function setCodigo_cliente($val) {$this->codigo_cliente = $val;}
function setCodigo_unico($val) {$this->codigo_unico = $val;}
function setRazon_social($val) {$this->razon_social = $val;}
function setNombre($val) {$this->nombre = $val;}
function setApellido($val) {$this->apellido = $val;}
function setClave($val) {$this->clave = $val;}
function setEmail($val) {$this->email = $val;}
function setCuit($val) {$this->cuit = $val;}
function setDomicilio($val) {$this->domicilio = $val;}
function setDomicilio_localidad($val) {$this->domicilio_localidad = $val;}
function setDomicilio_provincia($val) {$this->domicilio_provincia = $val;}
function setDomicilio_cp($val) {$this->domicilio_cp = $val;}
function setTel_movil($val) {$this->tel_movil = $val;}
function setTel_otro($val) {$this->tel_otro = $val;}
function setAcepta_basesycond($val) {$this->acepta_basesycond = $val;}
function setEstado($val) {$this->estado = $val;}
function setFechaalta($val) {$this->fechaalta = $val;}

//SELECT METHOD / LOAD
//==================================================================================================================================
function select($id)
{
	$sql =  "SELECT * FROM clientes WHERE idcliente = '$id'";
	$result =  $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		$this->idcliente = $row->idcliente;
		$this->idgrupo = $row->idgrupo;
		$this->codigo_cliente = $row->codigo_cliente;
		$this->codigo_unico = $row->codigo_unico;
		$this->razon_social = $row->razon_social;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->clave = $row->clave;
		$this->email = $row->email;
		$this->cuit = $row->cuit;
		$this->domicilio = $row->domicilio;
		$this->domicilio_localidad = $row->domicilio_localidad;
		$this->domicilio_provincia = $row->domicilio_provincia;
		$this->domicilio_cp = $row->domicilio_cp;
		$this->tel_movil = $row->tel_movil;
		$this->dni = $row->dni;
		$this->tel_otro = $row->tel_otro;
		$this->acepta_basesycond = $row->acepta_basesycond;
		$this->estado = $row->estado;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_codigo_unico($cu)
{
	$sql =  "SELECT * FROM clientes WHERE codigo_unico = '$cu'";
	$result =  $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		$this->idcliente = $row->idcliente;
		$this->idgrupo = $row->idgrupo;
		$this->codigo_cliente = $row->codigo_cliente;
		$this->codigo_unico = $row->codigo_unico;
		$this->razon_social = $row->razon_social;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->clave = $row->clave;
		$this->email = $row->email;
		$this->cuit = $row->cuit;
		$this->domicilio = $row->domicilio;
		$this->domicilio_localidad = $row->domicilio_localidad;
		$this->domicilio_provincia = $row->domicilio_provincia;
		$this->domicilio_cp = $row->domicilio_cp;
		$this->tel_movil = $row->tel_movil;
		$this->tel_otro = $row->tel_otro;
		$this->acepta_basesycond = $row->acepta_basesycond;
		$this->estado = $row->estado;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function select_X_codigo_cliente($cc)
{
	$sql 		= "SELECT * FROM clientes WHERE codigo_cliente = '$cc'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		$this->idcliente = $row->idcliente;
		$this->idgrupo = $row->idgrupo;
		$this->codigo_cliente = $row->codigo_cliente;
		$this->codigo_unico = $row->codigo_unico;
		$this->razon_social = $row->razon_social;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->clave = $row->clave;
		$this->email = $row->email;
		$this->cuit = $row->cuit;
		$this->domicilio = $row->domicilio;
		$this->domicilio_localidad = $row->domicilio_localidad;
		$this->domicilio_provincia = $row->domicilio_provincia;
		$this->domicilio_cp = $row->domicilio_cp;
		$this->tel_movil = $row->tel_movil;
		$this->tel_otro = $row->tel_otro;
		$this->acepta_basesycond = $row->acepta_basesycond;
		$this->estado = $row->estado;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function selectXDni($email)
{
	$sql 		= "SELECT * FROM clientes WHERE email = '$email'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		$this->idcliente = $row->idcliente;
		$this->idgrupo = $row->idgrupo;
		$this->codigo_cliente = $row->codigo_cliente;
		$this->codigo_unico = $row->codigo_unico;
		$this->razon_social = $row->razon_social;
		$this->nombre = $row->nombre;
		$this->apellido = $row->apellido;
		$this->clave = $row->clave;
		$this->email = $row->email;
		$this->cuit = $row->cuit;
		$this->domicilio = $row->domicilio;
		$this->domicilio_localidad = $row->domicilio_localidad;
		$this->domicilio_provincia = $row->domicilio_provincia;
		$this->domicilio_cp = $row->domicilio_cp;
		$this->tel_movil = $row->tel_movil;
		$this->tel_otro = $row->tel_otro;
		$this->acepta_basesycond = $row->acepta_basesycond;
		$this->estado = $row->estado;
		$this->fechaalta = $row->fechaalta;
		return true;
	}
	else return false;
}

function chequeoAltaPaso1($cliente, $unico) {
	$sql 	= "SELECT * FROM clientes WHERE codigo_cliente = '$cliente' and codigo_unico = '$unico'";
	
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		$email  = $row->email;
		$clave  = $row->clave;
		$estado = $row->estado;
		$nombre = $row->nombre;
		$apellido = $row->apellido;
				
		if(($estado == 'A' || $estado == 'C') && $email!='' && clave!='') return 3;
		if($estado == 'P') {
			$_SESSION['QLMS_PA_IDCLIENTE']	= $row->idcliente;
			$_SESSION['QLMS_PA_NOMBRE'] 			= $row->nombre;
			$_SESSION['QLMS_PA_APELLIDO'] 		= $row->apellido;
			$_SESSION['QLMS_PA_EMAIL']	 				= $row->email;
			return 1;				
		}	
	}
	else return 2;
}

function chequeoAltaPaso2($email, $clave) {
	$sql 	= "SELECT * FROM clientes WHERE email = '$email' and idcliente != ".$_SESSION["QLMS_PA_IDCLIENTE"];
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) return 2;
	
	$_SESSION["QLMS_PA_EMAIL"] = $email;
	$sql = "UPDATE clientes SET email = '$email', clave = '$clave' WHERE idcliente = ".$_SESSION["QLMS_PA_IDCLIENTE"];
	$result = $this->database->query($sql);
	return 1;
}

function activar($idcliente) {
	$sql = "UPDATE clientes SET estado = 'A', fechaalta = '".date("Y-m-d")."' WHERE idcliente = ".$idcliente;	
	$result = $this->database->query($sql);	
	return 1;
}

//DELETE
//==================================================================================================================================
function delete($id)
{
	$sql = "DELETE FROM clientes WHERE idcliente = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function delete_todo($id)
{
	$sql = "DELETE FROM concursos_clientes WHERE idcliente = '$id'";
	$result = $this->database->query($sql);
	$sql0 = "DELETE FROM puntos WHERE idcliente = '$id'";
	$result0 = $this->database->query($sql0);
	$sql1 = "DELETE FROM clientes WHERE idcliente = '$id'";
	$result1 = $this->database->query($sql1);
	return true;
}

// INSERT
//==================================================================================================================================
function validaInsert($codigo_unico)
{
	$sql = "SELECT * FROM clientes WHERE codigo_unico = '$codigo_unico' and estado = 'A'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
		return false;
	else
		return true;
}

function insert()
{
	$this->idcliente = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO clientes (idgrupo,codigo_cliente,codigo_unico,razon_social,nombre,apellido,clave,email,cuit,domicilio,domicilio_localidad,domicilio_provincia,domicilio_cp,tel_movil,tel_otro,acepta_basesycond,estado,fechaalta) VALUES ($this->idgrupo,$this->codigo_cliente,$this->codigo_unico,$this->razon_social,$this->nombre,$this->apellido,$this->clave,$this->email,$this->cuit,$this->domicilio,$this->domicilio_localidad,$this->domicilio_provincia,$this->domicilio_cp,$this->tel_movil,$this->tel_otro,$this->acepta_basesycond,$this->estado,'".date("Y-m-d")."')";
	$result = $this->database->query($sql);
	$this->idcliente = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==================================================================================================================================
function update($id)
{
	$this->prepare();
	$sql = "UPDATE clientes SET codigo_cliente = $this->codigo_cliente,idgrupo = $this->idgrupo,razon_social = $this->razon_social,nombre = $this->nombre,apellido = $this->apellido,clave = $this->clave,email = $this->email,cuit = $this->cuit,domicilio = $this->domicilio,domicilio_localidad = $this->domicilio_localidad,domicilio_provincia = $this->domicilio_provincia,domicilio_cp = $this->domicilio_cp,tel_movil = $this->tel_movil,tel_otro = $this->tel_otro,acepta_basesycond = $this->acepta_basesycond,estado = $this->estado WHERE idcliente = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function cambiaEstado($id,$estado){
	if($estado == 'A') 
		$sql = "UPDATE clientes SET fechaalta = '".date("Y-m-d")."', estado = '$estado' WHERE idcliente = '$id'";
	else
		$sql = "UPDATE clientes SET estado = '$estado' WHERE idcliente = '$id'";
	
	$result = $this->database->query($sql);
	
	
	$sql = "SELECT idgrupo FROM clientes WHERE idcliente = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) {
		if($row->idgrupo=="" || $row->idgrupo==NULL) {
			$sql = "UPDATE clientes SET idgrupo = 20 WHERE idcliente = '$id'";	
			$result = $this->database->query($sql);
		}
	}		
	return true;
}

function actualizaFecha($id) {	
	$sql = "UPDATE clientes SET fechaalta = '".date("Y-m-d")."' WHERE idcliente = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function actualizaDNI($dni,$id) {	
	$sql = "UPDATE clientes SET dni = '".$dni."' WHERE idcliente = '$id'";	
	$result = $this->database->query($sql);
	return true;
}

function actualizaSaldo($id){
	$puntos = 0;
	$sql 		= "select sum(puntos) as puntos from puntos where idcliente = ".$id;
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row3 = mysql_fetch_object($result)) {
		$puntos =	$row3->puntos;
	}
			
	$canjes = 0;
	$sql 		= "select sum(valor) as canjes from canjes where idcliente = ".$id." and estado <> 'anulado' and estado <> 'devuelto'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if ($row2 = mysql_fetch_object($result)) {
		$canjes =	$row2->canjes;
	}
	$_SESSION['QLMSF_puntos'] = ($puntos - $canjes);
	return ($puntos - $canjes);
}

//==================================================================================================================================
function prepare(){

	$this->idgrupo = str_replace("'", "", $this->idgrupo);
	$this->codigo_cliente = str_replace("'", "", $this->codigo_cliente);
	$this->codigo_unico = str_replace("'", "", $this->codigo_unico);
	$this->razon_social = str_replace("'", "", $this->razon_social);
	$this->nombre = str_replace("'", "", $this->nombre);
	$this->apellido = str_replace("'", "", $this->apellido);
	$this->clave = str_replace("'", "", $this->clave);
	$this->email = str_replace("'", "", $this->email);
	$this->cuit = str_replace("'", "", $this->cuit);
	$this->domicilio = str_replace("'", "", $this->domicilio);
	$this->domicilio_localidad = str_replace("'", "", $this->domicilio_localidad);
	$this->domicilio_provincia = str_replace("'", "", $this->domicilio_provincia);
	$this->domicilio_cp = str_replace("'", "", $this->domicilio_cp);
	$this->tel_movil = str_replace("'", "", $this->tel_movil);
	$this->tel_otro = str_replace("'", "", $this->tel_otro);
	$this->acepta_basesycond = str_replace("'", "", $this->acepta_basesycond);
	$this->estado = str_replace("'", "", $this->estado);
	
	if($this->idgrupo != '')											$this->idgrupo											= '\''.$this->idgrupo.'\'';															else $this->idgrupo		= '20';
	if($this->codigo_cliente != '')						$this->codigo_cliente					= '\''.$this->codigo_cliente.'\'';										else $this->codigo_cliente						= 'NULL';
	if($this->codigo_unico != '')							$this->codigo_unico						= '\''.$this->codigo_unico.'\'';											else $this->codigo_unico							= 'NULL';
	if($this->razon_social != '')							$this->razon_social							= '\''.addslashes($this->razon_social).'\'';	else $this->razon_social							= 'NULL';
	if($this->nombre != '')											$this->nombre											= '\''.addslashes($this->nombre).'\'';					else $this->nombre											= 'NULL';
	if($this->apellido != '')											$this->apellido										= '\''.addslashes($this->apellido).'\'';				else $this->apellido											= 'NULL';
	if($this->clave != '')													$this->clave													= '\''.$this->clave.'\'';																	else $this->clave													= 'NULL';
	if($this->email	!= '')													$this->email												= '\''.$this->email.'\'';																	else $this->email													= 'NULL';
	if($this->cuit != '')														$this->cuit														= '\''.$this->cuit.'\'';																		else $this->cuit														= 'NULL';
	if($this->domicilio != '')										$this->domicilio										= '\''.addslashes($this->domicilio).'\'';				else $this->domicilio										= 'NULL';
	if($this->domicilio_localidad != '')		$this->domicilio_localidad		= '\''.$this->domicilio_localidad.'\'';						else $this->domicilio_localidad		= 'NULL';
	if($this->domicilio_provincia != '')		$this->domicilio_provincia		= '\''.$this->domicilio_provincia.'\'';						else $this->domicilio_provincia		= 'NULL';
	if($this->domicilio_cp != '')								$this->domicilio_cp							= '\''.$this->domicilio_cp.'\'';											else $this->domicilio_cp							= 'NULL';
	if($this->tel_movil != '')										$this->tel_movil										= '\''.$this->tel_movil.'\'';														else $this->tel_movil										= 'NULL';
	if($this->tel_otro != '')											$this->tel_otro										= '\''.$this->tel_otro.'\'';															else $this->tel_otro											= 'NULL';
	if($this->acepta_basesycond != '')	$this->acepta_basesycond	= '\''.$this->acepta_basesycond.'\'';					else $this->acepta_basesycond	= 'NULL';
	if($this->estado != '')											$this->estado											= '\''.$this->estado.'\'';															else $this->estado											= 'A';
}

function resetea(){
	$this->codigo_cliente = '';
	$this->codigo_unico = '';
	$this->razon_social = '';
	$this->nombre = '';
	$this->apellido = '';
	$this->clave = '';
	$this->email	= '';
	$this->cuit = '';
	$this->domicilio = '';
	$this->domicilio_localidad = '';
	$this->domicilio_provincia = '';
	$this->domicilio_cp = '';
	$this->tel_movil = '';
	$this->tel_otro = '';
	$this->acepta_basesycond = '';
	$this->estado = '';
}

//==================================================================================================================================
function getCanjes()
{
	$this->database = new Database();
	$arreglo = array();
	$i = 0;

	$sql = "select c.*, pr.nombre as premio, pr.tipo as tipo, pr.chances, pr.imagen as fotopremio from canjes c, premios pr where c.idcliente = '$this->idcliente' and c.idpremio = pr.idpremio order by c.fecha desc";

	$result = $this->database->query($sql);
	$result = $this->database->result;
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcanje']						= $row->idcanje;
		$arreglo[$i]['idcliente']					= $row->idcliente;
		$arreglo[$i]['idpremio']					= $row->idpremio;
		$arreglo[$i]['tipo']						= $row->tipo;
		$arreglo[$i]['chances']						= $row->chances;
		$arreglo[$i]['premio']							= $row->premio;
		$arreglo[$i]['fotopremio']			= $row->fotopremio;
		$arreglo[$i]['estado']						= $row->estado;
		$arreglo[$i]['fecha']								= $row->fecha;
		$arreglo[$i]['email']							= $row->email;
		$arreglo[$i]['seguimiento']							= $row->seguimiento;
		$arreglo[$i]['valor']								= $row->valor;
		$arreglo[$i]['lugar_entrega']	= $row->lugar_entrega;
		$arreglo[$i]['observaciones']	= $row->observaciones;
		$i++;
	}
	//retornar el arreglo
	return $arreglo;
}

//==================================================================================================================================
function getMovimientos($orden,$limit='')
{
	$this->database = new Database();
	$arreglo = array();
	$i = 0;

	$sql.= "(select '' as idpremio, motivo as tipo, observaciones, puntos as numero, fecha as fecha, '' as estado from puntos where idcliente = '$this->idcliente') ";
	$sql.= " union all ";
	$sql.= "(select pr.idpremio, 'canje' as tipo, '' as observaciones, c.valor as numero, c.fecha as fecha, c.estado from canjes c, premios pr where c.idcliente = '$this->idcliente' and c.estado <> 'anulado' and c.estado <> 'devuelto' and c.idpremio = pr.idpremio)  ";
	$sql.= " union all ";
	$sql.= "(select pr.idpremio, 'canje' as tipo, '' as observaciones, '0' as numero, c.fecha as fecha, c.estado from canjes c, premios pr where c.idcliente = '$this->idcliente' and (c.estado = 'anulado' or c.estado = 'devuelto') and c.idpremio = pr.idpremio)  ";
	$sql.= "order by fecha ".$orden;
	
	if($limit != '') $sql .= ' limit 0,'.$limit;
	//echo $sql;
	$result = $this->database->query($sql);
	$result = $this->database->result;
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['tipo']					= $row->tipo;
		$arreglo[$i]['observaciones']		= $row->observaciones;
		$arreglo[$i]['idpremio']	= $row->idpremio;
		$arreglo[$i]['estado']		= $row->estado;
		$arreglo[$i]['numero']		= $row->numero;
		$arreglo[$i]['fecha']				= $row->fecha;
		$i++;
	}
	//retornar el arreglo
	return $arreglo;
}

//==================================================================================================================================
function dameSumaXConcepto($tabla,$campo,$concepto='',$estado1='',$estado2='') {
	$sql = "SELECT SUM(".$campo.") as sumatoria FROM ".$tabla." WHERE idcliente = '$this->idcliente'";
	
	if($estado1 != '') $sql .= " and estado <> '".$estado1."'";
	if($estado2 != '') $sql .= " and estado <> '".$estado2."'";
	
	if($concepto != '') $sql .= " and (motivo like '%".$concepto."%')";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row	= mysql_fetch_object($result))
	{
		if($row->sumatoria>0)
			return $row->sumatoria;
		else
			return 0;
	}
	else
		return 0;
}

//==================================================================================================================================
function dameChancesTotalesId($idp) {
	$sql = "SELECT SUM(puntos) as puntos FROM puntos WHERE idcliente = '$idp'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row	= mysql_fetch_object($result))
	{
		if($row->puntos>0)
			return $row->puntos;
		else
			return 0;
	}
	else
		return 0;
}

//==================================================================================================================================
function dameBalanceId($idp) {
	$sql2 = "select SUM(puntos) as ingresos from puntos where idcliente = '$idp'";
	$result2 = $this->database->query($sql2);
	$result2 = $this->database->result;
	if($row2 = mysql_fetch_object($result2))
	{
		if(intval($row2->ingresos) >= 0)
			$suma = intval($row2->ingresos);
		else
			$suma = 0;
	}
	else
		$suma		= 0;

	$sql3 = "select SUM(valor) as egresos from canjes where idcliente = '$idp' and estado <> 'anulado' and estado <> 'devuelto'";
	$result3 = $this->database->query($sql3);
	$result3 = $this->database->result;
	if($row3 = mysql_fetch_object($result3))
	{
		if(intval($row3->egresos) >= 0)
			$resta = intval($row3->egresos);
		else
			$resta = 0;
	}
	else
		$resta = 0;

	$resultado_final = intval($suma - $resta);
	return $resultado_final;
}

// class : end
}
?>