 <?php
/*------------------------------------------------------
CLASSNAME:        		listado
GENERATION DATE:	07.02.2017
CLASS FILE:       			class.listado.php
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/
include_once('class.database.php');
include_once('class.canje.php');
include_once('class.paginado.php');

//CLASS DECLARATION
//====================================================================================================
class listado
{ // class : begin

//ATTRIBUTE DECLARATION
//====================================================================================================
var $database;	// Instance of class database
var $paginado; 	// Instance of class paginado
var $pagina;
var $regxpag;
var $propagar;
 

//CONSTRUCTOR METHOD
//====================================================================================================
function listado($pagina=0, $regxpag=10000){
	if(!isset($_SESSION)) {session_start();}
	$this->pagina		= $pagina;
	$this->regxpag	= $regxpag;
}

//METHODS
//====================================================================================================
function compararFechas($primera, $segunda)
{
  $valoresPrimera 		= explode ('/', $primera);   
  $valoresSegunda	= explode ('/', $segunda); 

  $diaPrimera   	= $valoresPrimera[0];  
  $mesPrimera  	= $valoresPrimera[1];  
  $anyoPrimera	= $valoresPrimera[2]; 

  $diaSegunda  		= $valoresSegunda[0];  
  $mesSegunda 	= $valoresSegunda[1];  
  $anyoSegunda	= $valoresSegunda[2];

  $diasPrimeraJuliano 	= gregoriantojd($mesPrimera, $diaPrimera, $anyoPrimera);  
  $diasSegundaJuliano	= gregoriantojd($mesSegunda, $diaSegunda, $anyoSegunda);     

  if(!checkdate($mesPrimera, $diaPrimera, $anyoPrimera))
	{
    // "La fecha ".$primera." no es válida";
    return 0;
  }
	elseif(!checkdate($mesSegunda, $diaSegunda, $anyoSegunda))
	{
    // "La fecha ".$segunda." no es válida";
    return 0;
  }
	else
	  return  $diasPrimeraJuliano - $diasSegundaJuliano;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getProvinciasCombo(){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql 		= 'select * from provincias where 1 = 1 order by orden asc';
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idprovincia']	= $row->idprovincia;
		$arreglo[$i]['provincia']		= $row->provincia;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getLocalidadesCombo($provincia=''){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql = 'select * from localidades where 1 = 1';
	if($provincia	!='') $sql .= " and provincia = '".$provincia."'"; 
	$sql .= ' order by localidad asc';
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idlocalidad']	= $row->idlocalidad;
		$arreglo[$i]['localidad']		= $row->localidad;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getNoticias($buscar='', $tipo=''){
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	$fin = count($busqueda);
	
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from noticias where 1 = 1';
	if($tipo!="") $sql .= " and tipo = '$tipo'";
	if($fin>0)
	{
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (titulo like '%".$busqueda[$j]."%' or cuerpo like '%".$busqueda[$j]."%')";
		}
	}
	$sql .= ' order by estado desc, fecha_alta desc, idnoticia desc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idnoticia']		= $row['idnoticia'];
		$arreglo[$i]['tipo']					= $row['tipo'];
		$arreglo[$i]['estado']					= $row['estado'];
		$arreglo[$i]['titulo']					= stripslashes($row['titulo']);
		$arreglo[$i]['cuerpo']				= stripslashes($row['cuerpo']);
		$arreglo[$i]['fecha_alta']	= $row['fecha_alta'];
		$arreglo[$i]['imagen']			= stripslashes($row['imagen']);
		$arreglo[$i]['video']					= stripslashes($row['video']);
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getNoticiasFront($id='',$limit='', $tipo='N'){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql = "select * from noticias where tipo='$tipo' and idnoticia <> '".$id."' order by fecha_alta desc, idnoticia desc limit ".$limit;
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idnoticia']		= $row->idnoticia;
		$arreglo[$i]['titulo']					= $row->titulo;
		$arreglo[$i]['fecha_alta']	= $row->fecha_alta;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getConcursos($buscar='',$desde='',$hasta=''){
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	$fin = count($busqueda);
	
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from concursos where 1 = 1';
	if($fin>0)
	{
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (titulo like '%".$busqueda[$j]."%' or descripcion like '%".$busqueda[$j]."%')";
		}
	}
	if($desde != '') $sql .= " and (DATE_FORMAT(fecha_desde, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(fecha_hasta, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	$sql .= ' order by idconcurso asc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idconcurso']							= $row['idconcurso'];
		$arreglo[$i]['titulo']											= $row['titulo'];
		$arreglo[$i]['imagen']									= $row['imagen'];
		$arreglo[$i]['descripcion']						= $row['descripcion'];
		$arreglo[$i]['chances_minimas']	= $row['chances_minimas'];
		$arreglo[$i]['aviso_legal']						= $row['aviso_legal'];
		$arreglo[$i]['fecha_desde']					= $row['fecha_desde'];
		$arreglo[$i]['fecha_hasta']					= $row['fecha_hasta'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getParticipantesConcurso($desde='',$hasta='',$idconcurso){
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = "select * from concursos_clientes where idconcurso = '$idconcurso'";
	if($desde != '') $sql .= " and (DATE_FORMAT(fecha, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(fecha, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	$sql .= ' order by id asc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idcliente']	= $row['idcliente'];
		$arreglo[$i]['fecha']				= $row['fecha'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getParticipantesConcursoSinPaginar($desde='',$hasta='',$idconcurso)
{
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql = "select * from concursos_clientes where idconcurso = '$idconcurso'";
	if($desde != '') $sql .= " and (DATE_FORMAT(fecha, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(fecha, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	$sql .= ' order by id asc';
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcliente']	= $row->idcliente;
		$arreglo[$i]['fecha']				= $row->fecha;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getNroParticipantesConcurso($idconcurso)
{
	$this->database = new Database();
	$participantes	= 0;
	$sql 			= "select count(id) as participantes from concursos_clientes where idconcurso = '$idconcurso'";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		$participantes =	$row->participantes;
	return $participantes;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getMensajes($estado=''){
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select m.* from mensajes m, clientes c where m.idcliente = c.idcliente';
	if($estado!='') $sql .= " and m.estado = '".$estado."'";
	$sql .= ' order by m.fecha desc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idmensaje']	= $row['idmensaje'];
		$arreglo[$i]['fecha']					= $row['fecha'];
		$arreglo[$i]['mensaje']		= $row['mensaje'];
		$arreglo[$i]['estado']			= $row['estado'];
		$arreglo[$i]['idcliente']		= $row['idcliente'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//obtiene los datos de los administradores y operadores existentes en la tabla 'usuarios'
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getUsuariosSistema($buscar='',$tipo=''){
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from usuarios where 1 = 1';
	if($buscar!='') $sql .= " and usuario like '%".$buscar."%'";
	if($tipo!='') $sql .= " and tipo = '".$tipo."'";
	$sql .= ' order by usuario asc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idusuario']	= $row['idusuario'];
		$arreglo[$i]['tipo'] 				= $row['tipo'];
		$arreglo[$i]['usuario'] 		= $row['usuario'];
		$arreglo[$i]['clave'] 			= $row['clave'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//obtiene los datos de los operadores (tipo = 'O') existentes en la tabla 'usuarios'
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getOperadores($buscar=''){
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from usuarios where 1 = 1';
	if($buscar!='') $sql .= " and (usuario like '%".$buscar."%')";
	$sql .= ' order by usuario asc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idusuario']	= $row['idusuario'];
		$arreglo[$i]['usuario'] 		= $row['usuario'];
		$arreglo[$i]['clave'] 			= $row['clave'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getClientes($buscar='',$idcliente='',$estado='',$grupo='')
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from clientes where 1 = 1';
	$fin = count($busqueda);
	if($fin>0)
	{
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (razon_social like '%".$busqueda[$j]."%' or nombre like '%".$busqueda[$j]."%' or apellido like '%".$busqueda[$j]."%' or email like '%".$busqueda[$j]."%' or codigo_unico like '%".$busqueda[$j]."%' or codigo_cliente like '%".$busqueda[$j]."%')";
		}
	}
	if($idcliente != '') $sql .= ' and idcliente = \''.$idcliente.'\'';
	if($estado != '') $sql .= ' and estado = \''.$estado.'\'';
	if($grupo != '') $sql .= ' and idgrupo = \''.$grupo.'\'';
	$sql .= ' order by fechaalta desc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idcliente']										= $row['idcliente'];
		$arreglo[$i]['idgrupo']											= $row['idgrupo'];
		$arreglo[$i]['codigo_cliente']						= $row['codigo_cliente'];
		$arreglo[$i]['codigo_unico']							= $row['codigo_unico'];
		$arreglo[$i]['razon_social']							= stripslashes($row['razon_social']);
		$arreglo[$i]['nombre']											= stripslashes($row['nombre']);
		$arreglo[$i]['apellido']											= stripslashes($row['apellido']);
		$arreglo[$i]['clave']													= $row['clave'];
		$arreglo[$i]['email']													= $row['email'];
		$arreglo[$i]['cuit']														= $row['cuit'];
		$arreglo[$i]['domicilio']										= stripslashes($row['domicilio']);
		$arreglo[$i]['domicilio_localidad']		= $row['domicilio_localidad'];
		$arreglo[$i]['domicilio_provincia']		= $row['domicilio_provincia'];
		$arreglo[$i]['domicilio_cp']								= $row['domicilio_cp'];
		$arreglo[$i]['tel_movil']										= $row['tel_movil'];
		$arreglo[$i]['tel_otro']											= $row['tel_otro'];
		$arreglo[$i]['acepta_basesycond']	= $row['acepta_basesycond'];
		$arreglo[$i]['estado']											= $row['estado'];
		$arreglo[$i]['fechaalta']										= $row['fechaalta'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getClientesSinPaginar($buscar='',$estado='')
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql = 'select cli.*, gr.nombre as grupo from clientes cli, grupos gr where cli.idgrupo = gr.idgrupo ';
	$fin = count($busqueda);
	if($fin>0)
	{
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (cli.razon_social like '%".$busqueda[$j]."%' or cli.nombre like '%".$busqueda[$j]."%' or cli.apellido like '%".$busqueda[$j]."%' or cli.email like '%".$busqueda[$j]."%')";
		}
	}
	if($estado	!= '') $sql .= " and cli.estado = '".$estado."'";
	$sql .= ' order by cli.nombre asc';
	
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcliente']										= $row->idcliente;
		$arreglo[$i]['codigo_unico']							= $row->codigo_unico;
		$arreglo[$i]['codigo_cliente']							= $row->codigo_cliente;
		$arreglo[$i]['lastlog']							= $row->lastlog;
		$arreglo[$i]['grupo']											= stripslashes($row->grupo);
		$arreglo[$i]['razon_social']							= stripslashes($row->razon_social);
		$arreglo[$i]['nombre']											= stripslashes($row->nombre);
		$arreglo[$i]['apellido']											= stripslashes($row->apellido);
		$arreglo[$i]['clave']													= $row->clave;
		$arreglo[$i]['email']													= $row->email;
		$arreglo[$i]['domicilio']										= stripslashes($row->domicilio);
		$arreglo[$i]['localidad']										= $row->domicilio_localidad;
		$arreglo[$i]['provincia']										= $row->domicilio_provincia;
		$arreglo[$i]['domicilio_cp']								= $row->domicilio_cp;
		$arreglo[$i]['tel_movil']										= $row->tel_movil;
		$arreglo[$i]['tel_otro']											= $row->tel_otro;
		$arreglo[$i]['acepta_basesycond']	= $row->acepta_basesycond;
		$arreglo[$i]['estado']											= $row->estado;
		$arreglo[$i]['fechaalta']										= $row->fechaalta;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//obtiene el informe de la evolucion de las registraciones existentes en las tablas 'clientes'
//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getClientesRegistrados($desde,$hasta){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql = "select * from clientes where DATE_FORMAT(fechaalta, '%Y-%m-%d') >= STR_TO_DATE('$desde', '%d/%m/%Y') and DATE_FORMAT(fechaalta, '%Y-%m-%d') <= STR_TO_DATE('$hasta', '%d/%m/%Y') order by fechaalta asc";
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{		
		$arreglo[$i]['fechaalta']				= $row->fechaalta;
		$arreglo[$i]['idcliente']				= $row->idcliente;
		$arreglo[$i]['razon_social']	= $row->razon_social;
		$arreglo[$i]['nombre']					= $row->nombre;
		$arreglo[$i]['apellido']					= $row->apellido;
		$arreglo[$i]['email']							= $row->email;
		$arreglo[$i]['provincia']				= $row->domicilio_provincia;
		$arreglo[$i]['localidad']				= $row->domicilio_localidad;
		$arreglo[$i]['tel_otro']					= $row->tel_otro;
		$arreglo[$i]['tel_movil']				= $row->tel_movil;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCodigos($buscar='',$usado=''){
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = "select * from codigos where 1 = 1";
	if($buscar	!= '') $sql .= " and codigo like '%".$buscar."%'";
	if($usado	!= '') $sql .= " and usado = '".$usado."'";
	$sql .= " order by idcodigo asc";
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idcodigo']	= $row['idcodigo'];
		$arreglo[$i]['codigo']			= $row['codigo'];
		$arreglo[$i]['puntos']		= $row['puntos'];
		$arreglo[$i]['usado']			= $row['usado'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPuntosAsignados($desde='',$hasta='',$pdv='')
{
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select pt.*,cl.razon_social as nombre from puntos pt, clientes cl where pt.idcliente = cl.idcliente';
	if($desde != '') $sql .= " and (DATE_FORMAT(pt.fecha, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(pt.fecha, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	if($pdv	!= '') $sql .= " and pt.idcliente = '".$pdv."'";
	$sql .= ' order by pt.fecha_carga desc, pt.fecha desc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['identrada']				= $row['identrada'];
		$arreglo[$i]['idcliente']					= $row['idcliente'];
		$arreglo[$i]['nombre']						= $row['nombre'];
		$arreglo[$i]['puntos']						= $row['puntos'];
		$arreglo[$i]['fecha']								= $row['fecha'];
		$arreglo[$i]['motivo']							= $row['motivo'];
		$arreglo[$i]['observaciones']	= $row['observaciones'];
		$arreglo[$i]['fecha_carga']		= $row['fecha_carga'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

function getMovimientosManuales($idcli, $desde='', $hasta='') {
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select pt.* from puntos pt where pt.idcliente = '.$idcli;
	if($desde != '') $sql .= " and (DATE_FORMAT(pt.fecha, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(pt.fecha, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";	
	$sql .= ' order by pt.fecha_carga desc, pt.fecha desc';
	//echo $sql;
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['identrada']		= $row['identrada'];
		$arreglo[$i]['idcliente']		= $row['idcliente'];		
		$arreglo[$i]['puntos']			= $row['puntos'];
		$arreglo[$i]['fecha']			= $row['fecha'];
		$arreglo[$i]['motivo']			= $row['motivo'];
		$arreglo[$i]['observaciones']	= $row['observaciones'];
		$arreglo[$i]['fecha_carga']		= $row['fecha_carga'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPlanillaPuntos($desde='',$hasta='',$pdv='')
{
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql = 'select pt.*,cl.razon_social as nombre from puntos pt, clientes cl where pt.idcliente = cl.idcliente';
	if($desde != '') $sql .= " and (DATE_FORMAT(pt.fecha_carga, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(pt.fecha_carga, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	if($pdv	!= '') $sql .= " and pt.idcliente = '".$pdv."'";
	$sql .= ' order by pt.fecha_carga desc, pt.fecha desc';
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['identrada']				= $row->identrada;
		$arreglo[$i]['idcliente']					= $row->idcliente;
		$arreglo[$i]['nombre']						= stripslashes($row->nombre);
		$arreglo[$i]['puntos']						= $row->puntos;
		$arreglo[$i]['fecha']								= $row->fecha;
		$arreglo[$i]['motivo']							= $row->motivo;
		$arreglo[$i]['observaciones']	= $row->observaciones;
		$arreglo[$i]['fecha_carga']		= $row->fecha_carga;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPuntosCliente($idcliente)
{
	$this->database = new Database();
	$puntos	= 0;
	$sql 			= "select sum(puntos) as puntos from puntos where idcliente = '$idcliente'";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		$puntos =	$row->puntos;
	return $puntos;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPuntosCliente2($idcliente,$desde='',$hasta='')
{
	$this->database = new Database();
	$puntos	= 0;
	$sql = "select sum(puntos) as puntos from puntos where idcliente = '$idcliente'";
	if($desde != '') $sql .= " and (DATE_FORMAT(fecha_carga, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(fecha_carga, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		$puntos =	$row->puntos;
	return $puntos;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getUltimosPuntosCliente($idcliente)
{
	$this->database = new Database();
	$fecha		= '';
	$sql 			= "select max(fecha) as ultima_entrada from puntos where idcliente = '$idcliente'";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		$fecha =	$row->ultima_entrada;
	return $fecha;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCanjes($buscar='',$estado='',$desde='',$hasta='',$tipo='',$tipos='')
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
		
	$sql = 'select ca.*, pr.nombre as premio, pr.tipo as tipo, pr.chances, clnt.razon_social as cliente, clnt.email as email, clnt.codigo_unico as codigo_unico, clnt.tel_movil as movil, clnt.tel_otro as fijo from premios pr, clientes clnt, canjes ca where ca.idcliente = clnt.idcliente and ca.idpremio = pr.idpremio';
	if(count($busqueda)>0)
	{
		$fin = count($busqueda);
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (clnt.razon_social like '%".$busqueda[$j]."%' or clnt.codigo_unico like '%".$busqueda[$j]."%')";
		}
	}
	if($estado!='')	$sql .= " and ca.estado = '".$estado."'";
	if($desde != '') $sql .= " and (DATE_FORMAT(ca.fecha, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(ca.fecha, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	if($tipo!='')	$sql .= " and pr.tipo = '".$tipo."'";
	if($tipos!='')	$sql .= " and pr.tipo IN (".$tipos.")";
	$sql .= ' order by ca.idcanje desc';
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcanje']						= $row->idcanje;		
		$arreglo[$i]['idcliente']					= $row->idcliente;		
		$arreglo[$i]['idpremio']					= $row->idpremio;		
		$arreglo[$i]['tipo']									= $row->tipo;		
		$arreglo[$i]['chances']						= $row->chances;		
		$arreglo[$i]['estado']						= $row->estado;		
		$arreglo[$i]['fecha']								= $row->fecha;
		$arreglo[$i]['valor']								= $row->valor;		
		$arreglo[$i]['seguimiento']								= $row->seguimiento;		
		$arreglo[$i]['lugar_entrega']	= $row->lugar_entrega;		
		$arreglo[$i]['observaciones']	= $row->observaciones;		
		$arreglo[$i]['premio']							= $row->premio;
		$arreglo[$i]['cliente']							= $row->cliente;
		$arreglo[$i]['codigo_unico']		= $row->codigo_unico;
		$arreglo[$i]['email']								= $row->email;
		$arreglo[$i]['movil']								= $row->movil;
		$arreglo[$i]['fijo']										= $row->fijo;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCanjesPlanilla($buscar='',$estado='',$desde='',$hasta='',$tipo='')
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
		
	$sql = 'select ca.*, pr.nombre as premio, pr.tipo as tipo, pr.chances, clnt.nombre, clnt.apellido, clnt.razon_social, clnt.cuit, clnt.codigo_unico, clnt.email as email, clnt.tel_movil as movil, clnt.tel_otro as fijo from premios pr, clientes clnt, canjes ca where ca.idcliente = clnt.idcliente and ca.idpremio = pr.idpremio';
	if(count($busqueda)>0)
	{
		$fin = count($busqueda);
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (clnt.razon_social like '%".$busqueda[$j]."%')";
		}
	}
	if($estado!='')	$sql .= " and ca.estado = '".$estado."'";
	if($desde != '') $sql .= " and (DATE_FORMAT(ca.fecha, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(ca.fecha, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	if($tipo!='')	$sql .= " and pr.tipo = '".$tipo."'";
	$sql .= ' order by ca.idcanje desc';
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcanje']						= $row->idcanje;		
		$arreglo[$i]['codigo_unico']		= $row->codigo_unico;		
		$arreglo[$i]['cuit']									= $row->cuit;		
		$arreglo[$i]['idcliente']					= $row->idcliente;		
		$arreglo[$i]['idpremio']					= $row->idpremio;		
		$arreglo[$i]['tipo']									= $row->tipo;		
		$arreglo[$i]['chances']						= $row->chances;		
		$arreglo[$i]['estado']						= $row->estado;		
		$arreglo[$i]['fecha']								= $row->fecha;
		$arreglo[$i]['valor']								= $row->valor;		
		$arreglo[$i]['lugar_entrega']	= $row->lugar_entrega;		
		$arreglo[$i]['observaciones']	= $row->observaciones;		
		$arreglo[$i]['premio']							= $row->premio;
		$arreglo[$i]['cliente']							= $row->nombre.' '.$row->apellido;
		$arreglo[$i]['email']								= $row->email;
		$arreglo[$i]['movil']								= $row->movil;
		$arreglo[$i]['fijo']										= $row->fijo;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCanjesPlanillaSolicitados()
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
		
	$sql = 'select ca.*, pr.nombre as premio, pr.tipo as tipo, pr.chances, clnt.nombre, clnt.apellido, clnt.razon_social, clnt.cuit, clnt.codigo_unico, clnt.email as email, clnt.tel_movil as movil, clnt.tel_otro as fijo from premios pr, clientes clnt, canjes ca where ca.idcliente = clnt.idcliente and ca.idpremio = pr.idpremio';
	$sql .= " and ca.estado = 'solicitado'";
	$sql .= ' order by ca.idcanje desc';
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	$can = new canje();
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcanje']						= $row->idcanje;		
		$arreglo[$i]['codigo_unico']		= $row->codigo_unico;		
		$arreglo[$i]['cuit']									= $row->cuit;		
		$arreglo[$i]['idcliente']					= $row->idcliente;		
		$arreglo[$i]['idpremio']					= $row->idpremio;		
		$arreglo[$i]['tipo']									= $row->tipo;		
		$arreglo[$i]['chances']						= $row->chances;		
		$arreglo[$i]['estado']						= $row->estado;		
		$arreglo[$i]['fecha']								= $row->fecha;
		$arreglo[$i]['valor']								= $row->valor;		
		$arreglo[$i]['lugar_entrega']	= $row->lugar_entrega;		
		$arreglo[$i]['observaciones']	= $row->observaciones;		
		$arreglo[$i]['premio']							= $row->premio;
		$arreglo[$i]['cliente']							= $row->nombre." ".$row->apellido;
		$arreglo[$i]['email']								= $row->email;
		$arreglo[$i]['movil']								= $row->movil;
		$arreglo[$i]['fijo']										= $row->fijo;
		$i++;
		
		$can->insertLog($row->idcanje, "'en proceso'");
	}		
	
	//paso todos los solicitados a procesados
	$sql = "update canjes set estado = 'en proceso' where estado = 'solicitado'";
	$result = $this->database->query($sql);
	
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getLogscanje($idcanje)
{
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
		
	$sql = "select c.*, u.usuario from log_canjes c, usuarios u where c.idusuario = u.idusuario and c.idcanje = '$idcanje' order by c.fecha asc";
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idlog']			= $row->idlog;
		$arreglo[$i]['estado']	= $row->estado;
		$arreglo[$i]['fecha']			= $row->fecha;
		$arreglo[$i]['usuario']	= $row->usuario;		
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCanjesClienteTotal($idcliente)
{
	$this->database = new Database();
	$canjes	= 0;
	$sql 			= "select sum(valor) as canjes from canjes where idcliente = '$idcliente' and estado <> 'anulado' and estado <> 'devuelto'";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		$canjes =	$row->canjes;
	return $canjes;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCanjesClienteTotal2($idcliente,$desde='',$hasta='')
{
	$this->database = new Database();
	$canjes	= 0;
	$sql = "select sum(valor) as canjes from canjes where idcliente = '$idcliente' and estado <> 'anulado' and estado <> 'devuelto'";
	if($desde != '') $sql .= " and (DATE_FORMAT(fecha, '%Y-%m-%d') >= STR_TO_DATE('".$desde."', '%d/%m/%Y'))";
	if($hasta != '') $sql .= " and (DATE_FORMAT(fecha, '%Y-%m-%d') <= STR_TO_DATE('".$hasta."', '%d/%m/%Y'))";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		$canjes =	$row->canjes;
	return $canjes;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getUltimosCanjesCliente($idcliente)
{
	$this->database = new Database();
	$fecha		= '';
	$sql 			= "select max(fecha) as ultimo_canje from canjes where idcliente = '$idcliente'";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		$fecha =	$row->ultimo_canje;
	return $fecha;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getValorMaximo()
{
	$this->database = new Database();
	$fecha		= '';
	$sql 		= "select max(valor) as maximo from premios";
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	if ($row = mysql_fetch_object($result))
		return $row->maximo;
	return 1000;	
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPremios($buscar='',$campania='',$destacado='')
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from premios where 1 = 1';
	if(count($busqueda)>0)
	{
		$fin = count($busqueda);
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (nombre like '%".$busqueda[$j]."%' or detalle like '%".$busqueda[$j]."%')";
		}
	}	
	if($campania!='') $sql .= " and idcampania = '".$campania."'";
	if($destacado!='') $sql .= " and destacado = '".$destacado."'";
	$sql .= ' order by nombre asc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i = 0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idpremio']						= $row['idpremio'];		
		$arreglo[$i]['nombre']							= stripslashes($row['nombre']);		
		$arreglo[$i]['imagen']							= $row['imagen'];		
		$arreglo[$i]['tipo']										= $row['tipo'];
		$arreglo[$i]['idcampania']				= $row['idcampania'];
		$arreglo[$i]['detalle']								= stripslashes($row['detalle']);
		$arreglo[$i]['valor']									= $row['valor'];
		$arreglo[$i]['chances']							= $row['chances'];
		$arreglo[$i]['stock_inicial']				= $row['stock_inicial'];
		$arreglo[$i]['vigencia_desde']	= $row['vigencia_desde'];
		$arreglo[$i]['vigencia_hasta']	= $row['vigencia_hasta'];
		$arreglo[$i]['estado']							= $row['estado'];
		$arreglo[$i]['origen']								= $row['origen'];
		$arreglo[$i]['garantia']						= $row['garantia'];
		$arreglo[$i]['destacado']					= $row['destacado'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPremiosHome($fil_min='', $fil_max='', $fil_cam='', $fil_bus='')
{
	$busqueda = array();
	if($fil_bus != '') $busqueda = preg_split('/ /',$fil_bus);
	
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	//falta ver el tema de stock
	$sql = 'select p.* from premios p, premios_grupos pg where p.estado = "P" and p.idpremio = pg.idpremio and pg.idgrupo = "'.$_SESSION['QLMSF_idgrupo'].'"';
	if(count($busqueda)>0)
	{
		$fin = count($busqueda);
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (p.nombre like '%".$busqueda[$j]."%' or p.detalle like '%".$busqueda[$j]."%' or p.nombre_ch like '%".$busqueda[$j]."%' or p.detalle_ch like '%".$busqueda[$j]."%')";
		}
	}	
	if($fil_cam != '') $sql .= ' and p.idcampania = \''.$fil_cam.'\'';
	if($fil_min != '') $sql .= ' and p.valor >= \''.$fil_min.'\'';
	if($fil_max != '') $sql .= ' and p.valor <= \''.$fil_max.'\'';
	$sql .= ' order by p.nombre asc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i = 0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idpremio']						= $row['idpremio'];		
		$arreglo[$i]['nombre']							= stripslashes($row['nombre']);		
		$arreglo[$i]['nombre_ch']				= stripslashes($row['nombre_ch']);		
		$arreglo[$i]['imagen']							= $row['imagen'];		
		$arreglo[$i]['tipo']										= $row['tipo'];
		$arreglo[$i]['idcampania']				= $row['idcampania'];
		$arreglo[$i]['detalle']								= stripslashes($row['detalle']);
		$arreglo[$i]['detalle_ch']					= stripslashes($row['detalle_ch']);
		$arreglo[$i]['valor']									= $row['valor'];
		$arreglo[$i]['chances']							= $row['chances'];
		$arreglo[$i]['stock_inicial']				= $row['stock_inicial'];
		$arreglo[$i]['vigencia_desde']	= $row['vigencia_desde'];
		$arreglo[$i]['vigencia_hasta']	= $row['vigencia_hasta'];
		$arreglo[$i]['estado']							= $row['estado'];
		$arreglo[$i]['origen']								= $row['origen'];
		$arreglo[$i]['garantia']						= $row['garantia'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPremiosHomePopulares()
{
	$busqueda = array();
		
	//crear la conexion
	$this->database = new Database();
		
	//falta ver el tema de stock
	//$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances, count(c.idcanje) as canjes from premios p, canjes c where p.estado = "P" and p.idpremio = c.idpremio group by p.idpremio, p.nombre, p.imagen, p.chances order by p.nombre asc limit 4';
	$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances, count(c.idcanje) as canjes from premios p, premios_grupos pg, canjes c where p.estado = "P" and p.idpremio = c.idpremio and p.idpremio = pg.idpremio and pg.idgrupo = "'.$_SESSION['QLMSF_idgrupo'].'" group by p.idpremio, p.nombre, p.imagen, p.chances order by canjes desc limit 4';
	
	$result 	= $this->database->query($sql);
	$result 	= $this->database->result;
	
	$arreglo = array();	
	$i = 0;
	while($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idpremio']			= $row->idpremio;		
		$arreglo[$i]['nombre']				= stripslashes($row->nombre);		
		$arreglo[$i]['nombre_ch']	= stripslashes($row->nombre_ch);		
		$arreglo[$i]['imagen']				= $row->imagen;				
		$arreglo[$i]['valor']						= $row->valor;
		$arreglo[$i]['chances']				= $row->chances;		
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPremiosHomeAlcance($puntos)
{
	$busqueda = array();
		
	//crear la conexion
	$this->database = new Database();
		
	//falta ver el tema de stock
	//$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances from premios p where p.estado = "P" and p.valor <= '.$puntos.' order by p.nombre asc  limit 4';
	$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances from premios p, premios_grupos pg where p.estado = "P" and p.valor <= '.$puntos.' and p.idpremio = pg.idpremio and pg.idgrupo = "'.$_SESSION['QLMSF_idgrupo'].'" ORDER BY RAND() limit 4';
	
	$result	= $this->database->query($sql);
	$result = $this->database->result;
	
	$arreglo = array();	
	$i = 0;
	while($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idpremio']			= $row->idpremio;		
		$arreglo[$i]['nombre']				= stripslashes($row->nombre);		
		$arreglo[$i]['nombre_ch']	= stripslashes($row->nombre_ch);		
		$arreglo[$i]['imagen']				= $row->imagen;				
		$arreglo[$i]['valor']						= $row->valor;
		$arreglo[$i]['chances']				= $row->chances;		
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPremiosHomeNuevos()
{
	$busqueda = array();
		
	//crear la conexion
	$this->database = new Database();
		
	//falta ver el tema de stock
	//$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances from premios p where p.estado = "P" order by p.idpremio desc limit 4';
	$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances from premios p, premios_grupos pg where p.estado = "P" and p.idpremio = pg.idpremio and pg.idgrupo = "'.$_SESSION['QLMSF_idgrupo'].'" order by p.idpremio desc limit 4';
	
	$result	= $this->database->query($sql);
	$result = $this->database->result;
	
	$arreglo = array();	
	$i = 0;
	while($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idpremio']			= $row->idpremio;		
		$arreglo[$i]['nombre']				= stripslashes($row->nombre);		
		$arreglo[$i]['nombre_ch']	= stripslashes($row->nombre_ch);		
		$arreglo[$i]['imagen']				= $row->imagen;				
		$arreglo[$i]['valor']						= $row->valor;
		$arreglo[$i]['chances']				= $row->chances;		
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPremiosHomeDestacados()
{
	//crear la conexion
	$this->database = new Database();
		
	//falta ver el tema de stock
	//$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances from premios p where p.estado = "P" and destacado = "S" order by p.idpremio desc limit 4';
	$sql = 'select p.idpremio, p.nombre, p.nombre_ch, p.imagen, p.valor, p.chances from premios p, premios_grupos pg where p.estado = "P" and destacado = "S" and p.idpremio = pg.idpremio and pg.idgrupo = "'.$_SESSION['QLMSF_idgrupo'].'" order by RAND() limit 4';
	
	$result	= $this->database->query($sql);
	$result = $this->database->result;
	
	$arreglo = array();	
	$i = 0;
	while($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idpremio']			= $row->idpremio;		
		$arreglo[$i]['nombre']				= stripslashes($row->nombre);		
		$arreglo[$i]['nombre_ch']	= stripslashes($row->nombre_ch);		
		$arreglo[$i]['imagen']				= $row->imagen;				
		$arreglo[$i]['valor']						= $row->valor;
		$arreglo[$i]['chances']				= $row->chances;		
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getPremiosPlanilla($buscar='',$campania='')
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
		
	$sql = 'select * from premios where 1 = 1';
	if(count($busqueda)>0)
	{
		$fin = count($busqueda);
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (nombre like '%".$busqueda[$j]."%' or detalle like '%".$busqueda[$j]."%')";
		}
	}	
	if($campania!='') $sql .= " and idcampania = '".$campania."'";
	$sql .= ' order by nombre asc';
	
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idpremio']						= $row->idpremio;		
		$arreglo[$i]['nombre']							= $row->nombre;		
		$arreglo[$i]['tipo']										= $row->tipo;
		$arreglo[$i]['idcampania']				= $row->idcampania;
		$arreglo[$i]['detalle']								= $row->detalle;
		$arreglo[$i]['valor']									= $row->valor;
		$arreglo[$i]['chances']							= $row->chances;
		$arreglo[$i]['stock_inicial']				= $row->stock_inicial;
		$arreglo[$i]['vigencia_desde']	= $row->vigencia_desde;
		$arreglo[$i]['vigencia_hasta']	= $row->vigencia_hasta;
		$arreglo[$i]['estado']							= $row->estado;
		$arreglo[$i]['origen']								= $row->origen;
		$arreglo[$i]['garantia']						= $row->garantia;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCampanias($buscar='', $soloactivas=false)
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from campanias where 1 = 1';
	if(count($busqueda)>0)
	{
		$fin = count($busqueda);
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (nombre like '%".$busqueda[$j]."%')";
		}
	}	
	
	if($soloactivas) $sql .= " and (DATE(NOW()) >= fecha_inicial and  DATE(NOW()) <= fecha_final)";
	$sql .= ' order by fecha_inicial asc';
		
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i = 0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idcampania']		= $row['idcampania'];
		$arreglo[$i]['nombre']			= stripslashes($row['nombre']);		
		$arreglo[$i]['nombre_ch']		= stripslashes($row['nombre_ch']);		
		$arreglo[$i]['fecha_inicial']	= $row['fecha_inicial'];
		$arreglo[$i]['fecha_final']		= $row['fecha_final'];
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCampaniasCombo(){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql 		= 'select * from campanias where 1 = 1 order by fecha_inicial asc';
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcampania']	= $row->idcampania;
		$arreglo[$i]['nombre']				= $row->nombre;
		$arreglo[$i]['nombre_ch']	= $row->nombre_ch;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getSupermercadosCombo(){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql 		= 'select idcliente, razon_social from clientes where 1 = 1 order by razon_social asc';
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idcliente']				= $row->idcliente;
		$arreglo[$i]['razon_social']	= $row->razon_social;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getCodigosPremio($buscar='',$disponible='',$idpremio){
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();

	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);

	$sql = "select * from premios_codigos where idpremio = '$idpremio'";
	if($buscar != '') $sql .= " and codigo like '%".$buscar."%'";
	if($disponible	!= '') $sql .= " and disponible = '".$disponible."'";
	$sql .= ' order by disponible desc, fechaalta, idcodigo asc';
	
	//armar el arreglo de objetos
	$this->paginado->query($sql);

	$arreglo = array();
	$i=0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idcodigo']		= $row['idcodigo'];
		$arreglo[$i]['codigo']				= $row['codigo'];
		$arreglo[$i]['disponible']	= $row['disponible'];
		$arreglo[$i]['fechaalta']		= $row['fechaalta'];
		$i++;
	}
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getGrupos($buscar='')
{
	$busqueda = array();
	if($buscar != '') $busqueda = preg_split('/ /',$buscar);
	
	//crear la conexion
	$this->database = new Database();
	$this->database->OpenLink();
	$this->database->SelectDB();
		
	//crear e instancear el paginado
	$this->paginado = new paginado($this->database->link);
	$this->paginado->pagina($this->pagina);
	$this->paginado->porPagina($this->regxpag);
	
	$sql = 'select * from grupos where 1 = 1';
	if(count($busqueda)>0)
	{
		$fin = count($busqueda);
		for($j=0;$j<$fin;$j++)
		{
			$sql .= " and (nombre like '%".$busqueda[$j]."%' or nombre_ch like '%".$busqueda[$j]."%' or descripcion like '%".$busqueda[$j]."%' or descripcion_ch like '%".$busqueda[$j]."%')";
		}
	}	
	$sql .= ' order by nombre asc';
	
	//armar el arreglo de objetos	
	$this->paginado->query($sql);
	
	$arreglo = array();	
	$i = 0;
	while($row = $this->paginado->obtenerArray())
	{
		$arreglo[$i]['idgrupo']							= $row['idgrupo'];		
		$arreglo[$i]['nombre']							= stripslashes($row['nombre']);		
		$arreglo[$i]['nombre_ch']				= stripslashes($row['nombre_ch']);		
		$arreglo[$i]['descripcion']				= stripslashes($row['descripcion']);
		$arreglo[$i]['descripcion_ch']	= stripslashes($row['descripcion_ch']);
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getGruposCombo(){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;
	
	$sql 		= 'select * from grupos where 1 = 1 order by nombre asc';
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	while ($row = mysql_fetch_object($result))
	{
		$arreglo[$i]['idgrupo']				= $row->idgrupo;
		$arreglo[$i]['nombre']				= $row->nombre;
		$arreglo[$i]['nombre_ch']	= $row->nombre_ch;
		$i++;
	}		
	//retornar el arreglo
	return $arreglo;
}

//------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
function getGrupos_Premio($idpremio){
	$this->database = new Database();
	$arreglo = array();
	$i = 0;

	$sql = 'select idgrupo from premios_grupos where idpremio = \''.$idpremio.'\'';

	$result = $this->database->query($sql);
	$result = $this->database->result;
	while ($row = mysql_fetch_object($result)){
		$arreglo[$i]['idgrupo']	= $row->idgrupo;
		$i++;
	}
	//retornar el arreglo
	return $arreglo;
}

//PAGINADO
//====================================================================================================
function getPaginacion($vars=''){
	$this->paginado->variables($vars);	
	return '<span class="textCeleste12">'.$this->paginado->anterior().'</span><span class="textNegro12Bold">'.$this->paginado->nroPaginas().'</span><span class="textCeleste12">'.$this->paginado->siguiente().'</span>';
}

function getPaginacionReducida($vars=''){
	$this->paginado->variables($vars);	
	return "<span class='textoMarron12sinhover'><strong>".$this->paginado->anterior()."&#160;</strong></span><span class='textoMarron12sinhover'><strong>".$this->paginado->nroPaginas()."&#160;</strong></span><span class='textoMarron12sinhover'><strong>&#160;".$this->paginado->siguiente()."&#160;&#160;&#160;&#160;&#160;</strong></span>";
}

function getPaginacionFront($vars=''){
	$this->paginado->variables($vars);	
	return "<span class='linkPaginado'><strong>".$this->paginado->anterior_f()."&#160;</strong></span><span class='linkPaginado'><strong>".$this->paginado->nroPaginas()."&#160;</strong></span><span class='linkPaginado'><strong>&#160;".$this->paginado->siguiente_f()."&#160;&#160;&#160;&#160;&#160;</strong></span>";
}

function getTotalRegistros($vars=''){
	return $this->paginado->total();	
}

function getTotalPaginas($vars=''){
	return $this->paginado->totalPaginas();
}

// class : end
}
?>