<?php
/*-----------------------------------------------
CLASSNAME:        		codigo
GENERATION DATE:	15.02.2017
CLASS FILE:       			class.codigo.php
FOR MYSQL TABLE: 	premios_codigos
FOR MYSQL DB:     		aper_quilmes
--------------------------------------------------
CODE GENERATED BY: dixernet
-----------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//==============================================================================
class codigo
{ // class : begin

//ATTRIBUTE DECLARATION
//==============================================================================
var $idcodigo;   	// KEY ATTR. WITH AUTOINCREMENT

var $idpremio;		// (normal attribute)
var $idcliente;		// (normal attribute)
var $codigo;   		// (normal attribute)
var $disponible;	// (normal attribute)
var $fechauso; 	// (normal attribute)
var $fechaalta;  // (normal attribute)

var $database; 	// Instance of class database

//CONSTRUCTOR METHOD
//==============================================================================
function codigo() {
	$this->database = new Database();
}

//GETTER METHODS
//==============================================================================
function getIdcodigo() 		{return $this->idcodigo;}
function getIdpremio()			{return $this->idpremio;}
function getIdcliente()			{return $this->idcliente;}
function getCodigo() 				{return $this->codigo;}
function getDisponible()	{return $this->disponible;}
function getFechauso() 		{return $this->fechauso;}
function getFechaalta() 	{return $this->fechaalta;}

// SETTER METHODS
//==============================================================================
function setIdcodigo($val) 		{$this->idcodigo = $val; }
function setIdpremio($val)		{$this->idpremio = $val;}
function setIdcliente($val)			{$this->idcliente = $val;}
function setCodigo($val) 			{$this->codigo = $val;}
function setDisponible($val) 	{$this->disponible = $val;}
function setFechauso($val) 	{$this->fechauso = $val; }
function setFechaalta($val) 	{$this->fechaalta = $val; }

//SELECT METHOD / LOAD
//==============================================================================
function select($id)
{
	$sql 		= "SELECT * FROM premios_codigos WHERE idcodigo = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) 
	{
		$this->idcodigo 		= $row->idcodigo;
		$this->idpremio		= $row->idpremio;
		$this->idcliente		= $row->idcliente;
		$this->codigo 			= $row->codigo;
		$this->disponible	= $row->disponible;
		$this->fechauso 	= $row->fechauso;	
		$this->fechaalta 	= $row->fechaalta;	
		return true;
	}
	else return false;
}

function selectByCodigo($codigo)
{
	$sql 		= "SELECT * FROM premios_codigos WHERE codigo = '$codigo'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) 
	{
		$this->idcodigo 		= $row->idcodigo;
		$this->idpremio		= $row->idpremio;
		$this->idcliente		= $row->idcliente;
		$this->codigo 			= $row->codigo;
		$this->disponible	= $row->disponible;
		$this->fechauso 	= $row->fechauso;	
		$this->fechaalta 	= $row->fechaalta;	
		return true;
	}
	else return false;
}

//DELETE
//==============================================================================
function delete($id)
{
	$sql = "DELETE FROM premios_codigos WHERE idcodigo = '$id'";
	$result = $this->database->query($sql);
}

// INSERT
//==============================================================================
function validaInsert($id,$codigo)
{
	$sql 		= "SELECT * FROM premios_codigos WHERE idpremio = '$id' AND codigo = '$codigo'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) 
		return false;
	else
		return true;
}

function insert()
{
	$this->idcodigo = ''; // clear key for autoincrement
	if($this->idpremio	!= '')		$this->idpremio		= '\''.$this->idpremio.'\'';	else $this->idpremio	= 'NULL';
	if($this->idcliente	!= '')			$this->idcliente		= '\''.$this->idcliente.'\'';	else $this->idcliente	= 'NULL';
	if($this->codigo	!= '')				$this->codigo			= '\''.$this->codigo.'\'';			else $this->codigo			= 'NULL';
	if($this->fechauso	!= '')		$this->fechauso	= '\''.$this->fechauso.'\'';	else $this->fechauso	= 'NULL';
	$sql = "INSERT INTO premios_codigos (idpremio,idcliente,codigo,disponible,fechauso,fechaalta) VALUES ($this->idpremio,$this->idcliente,$this->codigo,1,$this->fechauso,'".date("Y-m-d")."')";
	$result = $this->database->query($sql);
	$this->idcodigo = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==============================================================================
function update($id)
{
	$sql = "UPDATE premios_codigos SET codigo = '$this->codigo' WHERE idcodigo = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function update2($id)
{
	$sql = "UPDATE premios_codigos SET disponible = '0',fechauso = '".date("Y-m-d")."' WHERE idcodigo = '$id'";
	$result = $this->database->query($sql);
	return true;
}

// class : end
}
?>