<?php
/*------------------------------------------------------
CLASSNAME:        		premio
GENERATION DATE:	13.02.2017
CLASS FILE:       			class.premio.php
FOR MYSQL TABLE: 	premios
FOR MYSQL DB:     		aper_quilmes
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//==================================================================================================
class premio
{ // class : begin


//ATTRIBUTE DECLARATION
//==================================================================================================
var $idpremio;   					// KEY ATTR. WITH AUTOINCREMENT

var $nombre;   						// (normal attribute)
var $nombre_ch;   			// (normal attribute)
var $imagen;   						// (normal attribute)
var $tipo;											// (normal attribute)
var $idcampania;					// (normal attribute)
var $detalle;  							// (normal attribute)
var $detalle_ch;  				// (normal attribute)
var $valor;   								// (normal attribute)
var $chances;   						// (normal attribute)
var $stock_inicial;				// (normal attribute)
var $vigencia_desde;	// (normal attribute)
var $vigencia_hasta;   // (normal attribute)
var $estado;  		 					// (normal attribute)
var $origen;   							// (normal attribute)
var $garantia;   					// (normal attribute)
var $destacado;   				// (normal attribute)

var $database; 						// Instance of class database

//CONSTRUCTOR METHOD
//==================================================================================================
function premio() {$this->database = new Database();}

//GETTER METHODS
//==================================================================================================
function getIdpremio() 						{return $this->idpremio;}
function getNombre() 							{return $this->nombre;}
function getNombre_ch() 				{return $this->nombre_ch;}
function getImagen() 							{return $this->imagen;}
function getTipo()										{return $this->tipo;}
function getIdcampania()				{return $this->idcampania;}
function getDetalle() 								{return $this->detalle;}
function getDetalle_ch() 					{return $this->detalle_ch;}
function getValor() 									{return $this->valor;}
function getChances() 						{return $this->chances;}
function getStock_inicial()				{return $this->stock_inicial;}
function getVigencia_desde()	{return $this->vigencia_desde;}
function getVigencia_hasta() 	{return $this->vigencia_hasta;}
function getEstado() 								{return $this->estado;}
function getOrigen() 								{return $this->origen;}
function getGarantia() 						{return $this->garantia;}
function getDestacado() 					{return $this->destacado;}

// SETTER METHODS
//==================================================================================================
function setIdpremio($val) 						{$this->idpremio =  $val;}
function setNombre($val) 							{$this->nombre =  $val;}
function setNombre_ch($val) 				{$this->nombre_ch =  $val;}
function setImagen($val) 							{$this->imagen =  $val;}
function setTipo($val)	  								{$this->tipo =  $val;}
function setIdcampania($val)	  		{$this->idcampania =  $val;}
function setDetalle($val) 							{$this->detalle =  $val;}
function setDetalle_ch($val) 					{$this->detalle_ch =  $val;}
function setValor($val) 									{$this->valor =  $val;}
function setChances($val) 						{$this->chances =  $val;}
function setStock_inicial($val)				{$this->stock_inicial =  $val;}
function setVigencia_desde($val)	{$this->vigencia_desde =  $val;}
function setVigencia_hasta($val) 	{$this->vigencia_hasta =  $val;}
function setEstado($val) 							{$this->estado =  $val;}
function setOrigen($val) 								{$this->origen =  $val;}
function setGarantia($val) 						{$this->garantia =  $val;}
function setDestacado($val) 					{$this->destacado =  $val;}

//SELECT METHOD / LOAD
//==================================================================================================
function select($id) {
	$sql 		= "SELECT pr.*, DATE_FORMAT(pr.vigencia_desde, '%d/%m/%Y') as vigencia_desde, DATE_FORMAT(pr.vigencia_hasta, '%d/%m/%Y') as vigencia_hasta FROM premios pr WHERE pr.idpremio = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) 
	{
		$this->idpremio 						= $row->idpremio;
		$this->nombre 							= $row->nombre;
		$this->nombre_ch					= $row->nombre_ch;
		$this->imagen 							= $row->imagen;
		$this->tipo											= $row->tipo;
		$this->idcampania					= $row->idcampania;
		$this->detalle 								= $row->detalle;
		$this->detalle_ch					= $row->detalle_ch;
		$this->valor 									= $row->valor;
		$this->chances 							= $row->chances;
		$this->stock_inicial				= $row->stock_inicial;
		$this->vigencia_desde	= $row->vigencia_desde;
		$this->vigencia_hasta 	= $row->vigencia_hasta;
		$this->estado 								= $row->estado;
		$this->origen 								= $row->origen;
		$this->garantia 						= $row->garantia;
		$this->destacado 					= $row->destacado;
		return true;
	} 
	else	return false;
}

function getNombreCampania($idpremio) {
	$sql 		= "SELECT c.nombre, c.nombre_ch FROM campanias c, premios p WHERE p.idcampania = c.idcampania and  p.idpremio = '$idpremio'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
		if(isset($_SESSION['QLMSF_idioma']) && $_SESSION['QLMSF_idioma']=="zh_CN")
			return $row->nombre_ch;
		else
			return $row->nombre;
	return '';
}

function dameCodigo($idpremio, $idcliente) {
	$sql 		= "SELECT codigo, idcodigo FROM premios_codigos WHERE disponible = 1 and idpremio = '$idpremio'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) {
		$codigo 	= $row->codigo;
		$idcodigo 	= $row->idcodigo;
		
		$sql = "UPDATE premios_codigos SET disponible = 0, idcliente = '$idcliente', fechauso = '".date("Y-m-d")."' WHERE idcodigo = '$idcodigo'";
		$result = $this->database->query($sql);
		
		return $codigo;
	}	
	return '';
}

//DELETE
//==================================================================================================
function delete($id) {
	$sql = "DELETE FROM premios WHERE idpremio = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function delete_todo($id) {
	$sql = "DELETE FROM premios_codigos WHERE idpremio = '$id'";
	$result = $this->database->query($sql);
	$sql1 = "DELETE FROM premios WHERE idpremio = '$id'";
	$result1 = $this->database->query($sql1);
	return true;
}

// INSERT
//==================================================================================================
function insert() {
	$this->idpremio = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO premios (nombre,nombre_ch,imagen,tipo,idcampania,detalle,detalle_ch,valor,chances,stock_inicial,vigencia_desde,vigencia_hasta,estado,origen,garantia,destacado) VALUES ($this->nombre,$this->nombre_ch,$this->imagen,$this->tipo,$this->idcampania,$this->detalle,$this->detalle_ch,$this->valor,$this->chances,$this->stock_inicial,STR_TO_DATE(".$this->vigencia_desde.", '%d/%m/%Y'),STR_TO_DATE(".$this->vigencia_hasta.", '%d/%m/%Y'),$this->estado,$this->origen,$this->garantia,$this->destacado)";
	$result = $this->database->query($sql);
	$this->idpremio = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==================================================================================================
function update($id) {
	$this->prepare();
	$sql = "UPDATE premios SET nombre = $this->nombre,nombre_ch = $this->nombre_ch,imagen = $this->imagen,tipo = $this->tipo,idcampania = $this->idcampania,detalle = $this->detalle,detalle_ch = $this->detalle_ch,valor = $this->valor,chances = $this->chances,stock_inicial = $this->stock_inicial,vigencia_desde = STR_TO_DATE(".$this->vigencia_desde.", '%d/%m/%Y'),vigencia_hasta = STR_TO_DATE(".$this->vigencia_hasta.", '%d/%m/%Y'),estado = $this->estado,origen = $this->origen,garantia = $this->garantia WHERE idpremio = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function cambiaEstado($id,$destacado){
	$sql = "UPDATE premios SET destacado = '$destacado' WHERE idpremio = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function cambiaPublicado($id,$estado){
	$sql = "UPDATE premios SET estado = '$estado' WHERE idpremio = '$id'"; 
	$result = $this->database->query($sql);
	return true;
}

function getStockReal($id) {
	$sql 		= "SELECT stock_inicial FROM premios WHERE idpremio = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	$stock_inicial = '';
	if($row = mysql_fetch_object($result))
		$stock_inicial 	= $row->stock_inicial;
	if($stock_inicial == '') return '-LIBRE-';
	
	$sql2 	= "SELECT COUNT(idcanje) as canjes FROM canjes WHERE idpremio = '$id' and estado <> 'anulado' and estado <> 'devuelto'";
	$result = $this->database->query($sql2);
	$result = $this->database->result;
	$canjes = 0;
	if($row = mysql_fetch_object($result))
		$canjes 	= $row->canjes;
	
	$stock_real = $stock_inicial - $canjes;
	if($stock_real > 0) return $stock_real;	else return 0;	
}

function estaEnGrupo($idpremio, $idgrupo) {
	$sql 		= "SELECT * FROM premios_grupos WHERE idpremio = '$idpremio' and idgrupo = '$idgrupo'";
	$result = $this->database->query($sql);
	$result = $this->database->result;	
	if($row = mysql_fetch_object($result))
		return true;
	else
		return false;
}

//========================================================================================
function prepare(){
	if($this->nombre != '')							$this->nombre								= '\''.$this->nombre.'\'';							else $this->nombre							= 'NULL';
	if($this->nombre_ch != '')				$this->nombre_ch					= '\''.$this->nombre_ch.'\'';				else $this->nombre_ch				= 'NULL';
	if($this->imagen != '')							$this->imagen								= '\''.$this->imagen.'\'';							else $this->imagen							= 'NULL';
	if($this->tipo != '')										$this->tipo											= '\''.$this->tipo.'\'';										else $this->tipo										= 'NULL';
	if($this->idcampania != '')				$this->idcampania					= '\''.$this->idcampania.'\'';				else $this->idcampania				= 'NULL';
	if($this->detalle != '')								$this->detalle								= '\''.$this->detalle.'\'';							else $this->detalle							= 'NULL';
	if($this->detalle_ch != '')					$this->detalle_ch					= '\''.$this->detalle_ch.'\'';					else $this->detalle_ch					= 'NULL';
	if($this->valor != '')									$this->valor										= '\''.$this->valor.'\'';									else $this->valor									= 'NULL';
	if($this->chances != '')							$this->chances							= '\''.$this->chances.'\'';						else $this->chances						= 'NULL';
	if($this->stock_inicial != '')				$this->stock_inicial				= '\''.$this->stock_inicial.'\'';			else $this->stock_inicial			= 'NULL';
	if($this->vigencia_desde != '')	$this->vigencia_desde	= '\''.$this->vigencia_desde.'\'';	else $this->vigencia_desde	= 'NULL';
	if($this->vigencia_hasta!= '')		$this->vigencia_hasta		= '\''.$this->vigencia_hasta.'\'';	else $this->vigencia_hasta	= 'NULL';
	if($this->estado!= '')								$this->estado								= '\''.$this->estado.'\'';							else $this->estado							= 'NULL';
	if($this->origen!= '')								$this->origen									= '\''.$this->origen.'\'';								else $this->origen								= 'NULL';
	if($this->garantia!= '')							$this->garantia							= '\''.$this->garantia.'\'';						else $this->garantia						= 'NULL';
	if($this->destacado!= '')					$this->destacado					= '\''.$this->destacado.'\'';					else $this->destacado					= 'N';
}

// class : end
}
?>