<?php
/*------------------------------------------------------
CLASSNAME:        		grupo
GENERATION DATE:	24.05.2018
CLASS FILE:       			class.grupo.php
FOR MYSQL TABLE: 	grupos
FOR MYSQL DB:     		aper_quilmes
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/
include_once('class.database.php');

//CLASS DECLARATION
//==================================================================================================
class grupo
{ // class : begin

//ATTRIBUTE DECLARATION
//==================================================================================================
var $idgrupo;   					// KEY ATTR. WITH AUTOINCREMENT

var $nombre;   					// (normal attribute)
var $nombre_ch;				// (normal attribute)
var $descripcion;				// (normal attribute)
var $descripcion_ch;	// (normal attribute)

var $database; 					// Instance of class database

//CONSTRUCTOR METHOD
//==================================================================================================
function grupo() {$this->database = new Database();}

//GETTER METHODS
//==================================================================================================
function getIdgrupo() 						{return $this->idgrupo;}
function getNombre() 						{return $this->nombre;}
function getNombre_ch() 			{return $this->nombre_ch;}
function getDescripcion()				{return $this->descripcion;}
function getDescripcion_ch()	{return $this->descripcion_ch;}

// SETTER METHODS
//==================================================================================================
function setIdgrupo($val) 						{$this->idgrupo =  $val;}
function setNombre($val) 						{$this->nombre =  $val;}
function setNombre_ch($val) 			{$this->nombre_ch =  $val;}
function setDescripcion($val)				{$this->descripcion =  $val;}
function setDescripcion_ch($val)	{$this->descripcion_ch =  $val;}

//SELECT METHOD / LOAD
//==================================================================================================
function select($id)
{
	$sql 		= "SELECT * FROM grupos WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) 
	{
		$this->idgrupo 						= $row->idgrupo;
		$this->nombre 						= $row->nombre;
		$this->nombre_ch 			= $row->nombre_ch;
		$this->descripcion				= $row->descripcion;
		$this->descripcion_ch	= $row->descripcion_ch;
		return true;
	} 
	else	return false;
}

//DELETE
//==================================================================================================
function delete($id)
{
	$sql = "DELETE FROM grupos WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function delete_todo($id)
{
	$sql = "DELETE FROM premios_grupos WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	$sql1 = "DELETE FROM grupos WHERE idgrupo = '$id'";
	$result1 = $this->database->query($sql1);
	return true;
}

// INSERT
//==================================================================================================
function insert()
{
	$this->idgrupo = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO grupos (nombre,nombre_ch,descripcion,descripcion_ch) VALUES ($this->nombre,$this->nombre_ch,$this->descripcion,$this->descripcion_ch)";
	$result = $this->database->query($sql);
	$this->idgrupo = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==================================================================================================
function update($id)
{
	$this->prepare();
	$sql = "UPDATE grupos SET nombre = $this->nombre, nombre_ch = $this->nombre_ch, descripcion = $this->descripcion, descripcion_ch = $this->descripcion_ch WHERE idgrupo = '$id'";
	$result = $this->database->query($sql);
	return true;
}

//==================================================================================================
function prepare(){
	if($this->nombre != '')							$this->nombre							= '\''.$this->nombre.'\'';							else $this->nombre							= 'NULL';
	if($this->nombre_ch != '')				$this->nombre_ch				= '\''.$this->nombre_ch.'\'';				else $this->nombre_ch				= 'NULL';
	if($this->descripcion != '')				$this->descripcion				= '\''.$this->descripcion.'\'';				else $this->descripcion				= 'NULL';
	if($this->descripcion_ch != '')	$this->descripcion_ch	= '\''.$this->descripcion_ch.'\'';	else $this->descripcion_ch	= 'NULL';
}

// class : end
}
?>