<?php
/*---------------------------------------------
CLASSNAME:        		puntos
GENERATION DATE:	22.02.2017
CLASS FILE:       			class.puntos.php
FOR MYSQL TABLE:	puntos
FOR MYSQL DB:     		aper_quilmes
------------------------------------------------
CODE GENERATED BY: dixernet
---------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//=============================================================================================
class puntos
{ // class : begin

//ATTRIBUTE DECLARATION
//=============================================================================================
var $identrada;  				// KEY ATTR. WITH AUTOINCREMENT

var $idcliente;   					// (normal attribute)
var $puntos;   						// (normal attribute)
var $fecha;   							// (normal attribute)
var $observaciones;	// (normal attribute)
var $motivo;   						// (normal attribute)
var $fecha_carga;			// (normal attribute)

var $database;					// Instance of class database

//CONSTRUCTOR METHOD
//=============================================================================================
function puntos()
{
	$this->database = new Database();
}

//GETTER METHODS
//=============================================================================================
function getIdentrada()					{return $this->identrada;}
function getIdcliente() 					{return $this->idcliente;}
function getPuntos() 							{return $this->puntos;}
function getFecha() 							{return $this->fecha;}
function getObservaciones()	{return $this->observaciones;}
function getMotivo() 							{return $this->motivo;}
function getFecha_carga()			{return $this->fecha_carga;}

// SETTER METHODS
//=============================================================================================
function setIdentrada($val)					{$this->identrada =  $val;}
function setIdcliente($val) 					{$this->idcliente =  $val;}
function setPuntos($val) 						{$this->puntos =  $val;}
function setFecha($val) 							{$this->fecha =  $val;}
function setObservaciones($val)	{$this->observaciones =  $val;}
function setMotivo($val) 							{$this->motivo =  $val;}
function setFecha_carga($val)		{$this->fecha_carga =  $val;}

//SELECT METHOD / LOAD
//=============================================================================================
function select($id)
{
	$sql 		= "SELECT * FROM puntos WHERE identrada = '$id'";
	//echo $sql;
	//exit;
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result)) 
	{
		$this->identrada					= $row->identrada;
		$this->idcliente 						= $row->idcliente;
		$this->puntos 							= $row->puntos;
		$this->fecha 								= $row->fecha;
		$this->observaciones	= $row->observaciones;
		$this->motivo 							= $row->motivo;
		$this->fecha_carga			= $row->fecha_carga;
		return true;
	}
	else	return false;
}

//DELETE
//=============================================================================================
function delete($id)
{
	$sql = "DELETE FROM puntos WHERE identrada = '$id'";
	$result = $this->database->query($sql);
	return true;
}

// INSERT
//=============================================================================================
function insert()
{
	$this->identrada = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO puntos (idcliente,puntos,fecha,observaciones,motivo,fecha_carga) VALUES ($this->idcliente,$this->puntos,STR_TO_DATE(".$this->fecha.", '%d/%m/%Y'),$this->observaciones,$this->motivo,$this->fecha_carga)";
	$result = $this->database->query($sql);
	$this->identrada = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//=============================================================================================
function update($id)
{
	$this->prepare();
	$sql = "UPDATE puntos SET idcliente = $this->idcliente,puntos = $this->puntos,observaciones = $this->observaciones,motivo = $this->motivo WHERE identrada = '$id'";
	$result = $this->database->query($sql);
	return true;
}

//=============================================================================================
function prepare(){
	if($this->idcliente != '')					$this->idcliente						= '\''.$this->idcliente.'\'';						else $this->idcliente						= 'NULL';
	if($this->puntos != '')						$this->puntos							= '\''.$this->puntos.'\'';							else $this->puntos							= 'NULL';
	if($this->fecha	!= '')								$this->fecha								= '\''.$this->fecha.'\'';									else $this->fecha									= '\''.date('Y-m-d').'\'';
	if($this->observaciones	!= '')	$this->observaciones	= '\''.$this->observaciones.'\'';	else $this->observaciones	= 'NULL';
	if($this->motivo	!= '')							$this->motivo							= '\''.$this->motivo.'\'';								else $this->motivo								= 'NULL';
	if($this->fecha_carga	!= '')		$this->fecha_carga			= '\''.$this->fecha_carga.'\'';			else $this->fecha_carga			= 'NULL';
}

function resetea(){
	$this->idcliente = '';
	$this->puntos = '';
	$this->fecha	= '';
	$this->observaciones	= '';
	$this->motivo	= '';
	$this->fecha_carga	= '';
}

// class : end
}
?>