<?php
/*------------------------------------------------------
CLASSNAME:        			concurso
GENERATION DATE: 	20.02.2017
CLASS FILE:       				class.concurso.php
FOR MYSQL TABLE:  	concursos
FOR MYSQL DB:     			aper_quilmes
--------------------------------------------------------
CODE GENERATED BY: dixernet
------------------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//========================================================================================
class concurso
{ // class : begin

//ATTRIBUTE DECLARATION
//========================================================================================
var $idconcurso;  					// KEY ATTR. WITH AUTOINCREMENT

var $titulo;  										// (normal attribute)
var $imagen;									// (normal attribute)
var $descripcion;						// (normal attribute)
var $chances_minimas;	// (normal attribute)
var $aviso_legal;						// (normal attribute)
var $fecha_desde;				// (normal attribute)
var $fecha_hasta;					// (normal attribute)

var $database; 							// Instance of class database

//CONSTRUCTOR METHOD
//========================================================================================
function concurso() {$this->database = new Database();}

//GETTER METHODS
//========================================================================================
function getIdconcurso() 						{return $this->idconcurso;}
function getTitulo() 											{return $this->titulo;}
function getImagen()										{return $this->imagen;}
function getDescripcion() 						{return $this->descripcion;}
function getChances_minimas()	{return $this->chances_minimas;}
function getAviso_legal()							{return $this->aviso_legal;}
function getFecha_desde()					{return $this->fecha_desde;}
function getFecha_hasta()					{return $this->fecha_hasta;}

// SETTER METHODS
//========================================================================================
function setIdconcurso($val) 						{$this->idconcurso = $val;}
function setTitulo($val) 											{$this->titulo = $val;}
function setImagen($val)									{$this->imagen = $val;}
function setDescripcion($val) 						{$this->descripcion = $val;}
function setChances_minimas($val)	{$this->chances_minimas = $val;}
function setAviso_legal($val)							{$this->aviso_legal = $val;}
function setFecha_desde($val)					{$this->fecha_desde = $val;}
function setFecha_hasta($val)					{$this->fecha_hasta = $val;}

//SELECT METHOD / LOAD
//========================================================================================
function select($id)
{
	$sql 		= "SELECT c.*, DATE_FORMAT(c.fecha_desde, '%d/%m/%Y') as fecha_desde, DATE_FORMAT(c.fecha_hasta, '%d/%m/%Y') as fecha_hasta FROM concursos c WHERE c.idconcurso = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		$this->idconcurso 						= $row->idconcurso;
		$this->titulo 										= $row->titulo;
		$this->imagen									= $row->imagen;
		$this->descripcion 					= $row->descripcion;
		$this->chances_minimas	= $row->chances_minimas;
		$this->aviso_legal						= $row->aviso_legal;
		$this->fecha_desde				= $row->fecha_desde;
		$this->fecha_hasta					= $row->fecha_hasta;
		return true;
	}
	else return false;
}

//DELETE
//========================================================================================
function delete($id)
{
	$sql = "DELETE FROM concursos WHERE idconcurso = '$id'";
	$result = $this->database->query($sql);
	return true;
}

function delete_todo($id)
{
	$sql = "DELETE FROM concursos_clientes WHERE idconcurso = '$id'";
	$result = $this->database->query($sql);
	$sql1 = "DELETE FROM concursos WHERE idconcurso = '$id'";
	$result1 = $this->database->query($sql1);
	return true;
}

// INSERT
//========================================================================================
function insert()
{
	$this->idconcurso = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO concursos (titulo,imagen,descripcion,chances_minimas,aviso_legal,fecha_desde,fecha_hasta) VALUES ($this->titulo,$this->imagen,$this->descripcion,$this->chances_minimas,$this->aviso_legal,STR_TO_DATE(".$this->fecha_desde.", '%d/%m/%Y'),STR_TO_DATE(".$this->fecha_hasta.", '%d/%m/%Y'))";
	$result = $this->database->query($sql);
	$this->idconcurso = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//========================================================================================
function update($id)
{
	$this->prepare();
	$sql = "UPDATE concursos SET titulo = $this->titulo,imagen = $this->imagen,descripcion = $this->descripcion,chances_minimas = $this->chances_minimas,aviso_legal = $this->aviso_legal,fecha_desde = STR_TO_DATE(".$this->fecha_desde.", '%d/%m/%Y'),fecha_hasta = STR_TO_DATE(".$this->fecha_hasta.", '%d/%m/%Y') WHERE idconcurso = '$id'";
	$result = $this->database->query($sql);
	return true;
}

//========================================================================================
function prepare(){
	if($this->titulo != '')											$this->titulo											= '\''.$this->titulo.'\'';											else $this->titulo											= 'NULL';
	if($this->imagen != '')									$this->imagen									= '\''.$this->imagen.'\'';									else $this->imagen									= 'NULL';
	if($this->descripcion	!= '')						$this->descripcion						= '\''.$this->descripcion.'\'';						else $this->descripcion						= 'NULL';
	if($this->chances_minimas != '')	$this->chances_minimas	= '\''.$this->chances_minimas.'\'';	else $this->chances_minimas	= 'NULL';
	if($this->aviso_legal != '')						$this->aviso_legal						= '\''.$this->aviso_legal.'\'';						else $this->aviso_legal						= 'NULL';
	if($this->fecha_desde != '')					$this->fecha_desde				= '\''.$this->fecha_desde.'\'';					else $this->fecha_desde					= 'NULL';
	if($this->fecha_hasta != '')					$this->fecha_hasta					= '\''.$this->fecha_hasta.'\'';					else $this->fecha_hasta					= 'NULL';
}

// class : end
}
?>