<?php
/*------------------------------------------------
CLASSNAME:        		campania
GENERATION DATE:	15.02.2017
CLASS FILE:       			class.campania.php
FOR MYSQL TABLE: 	campanias
FOR MYSQL DB:     		aper_quilmes
---------------------------------------------------
CODE GENERATED BY: dixernet
-------------------------------------------------*/

include_once('class.database.php');

//CLASS DECLARATION
//==================================================================================================================================
class campania
{ // class : begin

//ATTRIBUTE DECLARATION
//==================================================================================================================================
var $idcampania;   // KEY ATTR. WITH AUTOINCREMENT

var $nombre;   			// (normal attribute)
var $nombre_ch;		// (normal attribute)
var $fecha_inicial;	// (normal attribute)
var $fecha_final;   	// (normal attribute)

var $database; 			// Instance of class database


//CONSTRUCTOR METHOD
//==================================================================================================================================
function campania() {$this->database = new Database();}

//GETTER METHODS
//==================================================================================================================================
function getIdcampania() {return $this->idcampania;}
function getNombre() {return $this->nombre;}
function getNombre_ch() {return $this->nombre_ch;}
function getFecha_inicial() {return $this->fecha_inicial;}
function getFecha_final() {return $this->fecha_final;}

// SETTER METHODS
//==================================================================================================================================
function setIdcampania($val) {$this->idcampania =  $val;}
function setNombre($val) {$this->nombre =  $val;}
function setNombre_ch($val) {$this->nombre_ch =  $val;}
function setFecha_inicial($val) {$this->fecha_inicial =  $val;}
function setFecha_final($val) {$this->fecha_final =  $val;}

//SELECT METHOD / LOAD
//==================================================================================================================================
function select($id)
{
	$sql 		= "SELECT c.*, DATE_FORMAT(c.fecha_inicial, '%d/%m/%Y') as fecha_inicial, DATE_FORMAT(c.fecha_final, '%d/%m/%Y') as fecha_final FROM campanias c WHERE c.idcampania = '$id'";
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		$this->idcampania 	= $row->idcampania;
		$this->nombre 				= $row->nombre;
		$this->nombre_ch 	= $row->nombre_ch;
		$this->fecha_inicial	= $row->fecha_inicial;
		$this->fecha_final 		= $row->fecha_final;
		return true;
	}
	else return false;
}

//DELETE
//==================================================================================================================================
function delete($id)
{
	$sql = "SELECT * from premios where idcampania = ".$id;
	$result = $this->database->query($sql);
	$result = $this->database->result;
	if($row = mysql_fetch_object($result))
	{
		return false;
	}	else {
		$sql = "DELETE FROM campanias WHERE idcampania = '$id'";
		$result = $this->database->query($sql);
		return true;
	}	
}

// INSERT
//==================================================================================================================================
function insert()
{
	$this->idcampania = ''; // clear key for autoincrement
	$this->prepare();
	$sql = "INSERT INTO campanias (nombre,nombre_ch,fecha_inicial,fecha_final) VALUES ($this->nombre,$this->nombre_ch,STR_TO_DATE(".$this->fecha_inicial.", '%d/%m/%Y'),STR_TO_DATE(".$this->fecha_final.", '%d/%m/%Y'))";
	$result = $this->database->query($sql);
	$this->idcampania = mysql_insert_id($this->database->link);
	return true;
}

// UPDATE
//==================================================================================================================================
function update($id)
{
	$this->prepare();
	$sql = "UPDATE campanias SET nombre = $this->nombre,nombre_ch = $this->nombre_ch,fecha_inicial = STR_TO_DATE(".$this->fecha_inicial.", '%d/%m/%Y'),fecha_final = STR_TO_DATE(".$this->fecha_final.", '%d/%m/%Y') WHERE idcampania = '$id'";
	$result = $this->database->query($sql);
	return true;
}

//==================================================================================================================================
function prepare(){
	if($this->nombre != '')					$this->nombre					= '\''.$this->nombre.'\'';					else $this->nombre					= 'NULL';
	if($this->nombre_ch != '')		$this->nombre_ch		= '\''.$this->nombre_ch.'\'';		else $this->nombre_ch		= 'NULL';
	if($this->fecha_inicial != '')	$this->fecha_inicial	= '\''.$this->fecha_inicial.'\'';	else $this->fecha_inicial	= 'NULL';
	if($this->fecha_final!= '')			$this->fecha_final		= '\''.$this->fecha_final.'\'';		else $this->fecha_final		= 'NULL';
}

// class : end
}
?>